//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Data.DAL.Mcambio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class McambioEntities : DbContext
    {
        public McambioEntities()
            : base("name=McambioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_chilefx_deal_sce> tbl_chilefx_deal_sce { get; set; }
    
        public virtual ObjectResult<CambioDeEstadoCFXT_Result> CambioDeEstadoCFXT(string rut, Nullable<int> gb_folio, string gb_estado, Nullable<int> gb_cod_estado_contable, string gb_canal, string gb_responsable, ObjectParameter ls_ejecucion, ObjectParameter ls_codret, ObjectParameter ls_msgret)
        {
            var rutParameter = rut != null ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(string));
    
            var gb_folioParameter = gb_folio.HasValue ?
                new ObjectParameter("gb_folio", gb_folio) :
                new ObjectParameter("gb_folio", typeof(int));
    
            var gb_estadoParameter = gb_estado != null ?
                new ObjectParameter("gb_estado", gb_estado) :
                new ObjectParameter("gb_estado", typeof(string));
    
            var gb_cod_estado_contableParameter = gb_cod_estado_contable.HasValue ?
                new ObjectParameter("gb_cod_estado_contable", gb_cod_estado_contable) :
                new ObjectParameter("gb_cod_estado_contable", typeof(int));
    
            var gb_canalParameter = gb_canal != null ?
                new ObjectParameter("gb_canal", gb_canal) :
                new ObjectParameter("gb_canal", typeof(string));
    
            var gb_responsableParameter = gb_responsable != null ?
                new ObjectParameter("gb_responsable", gb_responsable) :
                new ObjectParameter("gb_responsable", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CambioDeEstadoCFXT_Result>("CambioDeEstadoCFXT", rutParameter, gb_folioParameter, gb_estadoParameter, gb_cod_estado_contableParameter, gb_canalParameter, gb_responsableParameter, ls_ejecucion, ls_codret, ls_msgret);
        }
    
        public virtual ObjectResult<ConsultaDealsDisponible_Result> ConsultaDealsDisponible(string rutCliente, string tipoTransaccion, ObjectParameter ls_codret, ObjectParameter ls_msgret)
        {
            var rutClienteParameter = rutCliente != null ?
                new ObjectParameter("rutCliente", rutCliente) :
                new ObjectParameter("rutCliente", typeof(string));
    
            var tipoTransaccionParameter = tipoTransaccion != null ?
                new ObjectParameter("tipoTransaccion", tipoTransaccion) :
                new ObjectParameter("tipoTransaccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultaDealsDisponible_Result>("ConsultaDealsDisponible", rutClienteParameter, tipoTransaccionParameter, ls_codret, ls_msgret);
        }
    
        public virtual ObjectResult<CrearDealChileFxTesoreria_Result> CrearDealChileFxTesoreria(string p_rutCliente, string p_nombreCliente, string p_parMoneda1, string p_parMoneda2, Nullable<double> p_precioCliente, Nullable<System.DateTime> p_fechaValuta, Nullable<int> p_codBcoCentral, Nullable<double> p_monto_me, Nullable<System.DateTime> p_fechaTransaccion, Nullable<double> p_tipoCambioPizarra, string p_tipoTransaccion, string p_identificadorConsulta, ObjectParameter ls_folio, ObjectParameter ls_msgret, ObjectParameter ls_codret)
        {
            var p_rutClienteParameter = p_rutCliente != null ?
                new ObjectParameter("p_rutCliente", p_rutCliente) :
                new ObjectParameter("p_rutCliente", typeof(string));
    
            var p_nombreClienteParameter = p_nombreCliente != null ?
                new ObjectParameter("p_nombreCliente", p_nombreCliente) :
                new ObjectParameter("p_nombreCliente", typeof(string));
    
            var p_parMoneda1Parameter = p_parMoneda1 != null ?
                new ObjectParameter("p_parMoneda1", p_parMoneda1) :
                new ObjectParameter("p_parMoneda1", typeof(string));
    
            var p_parMoneda2Parameter = p_parMoneda2 != null ?
                new ObjectParameter("p_parMoneda2", p_parMoneda2) :
                new ObjectParameter("p_parMoneda2", typeof(string));
    
            var p_precioClienteParameter = p_precioCliente.HasValue ?
                new ObjectParameter("p_precioCliente", p_precioCliente) :
                new ObjectParameter("p_precioCliente", typeof(double));
    
            var p_fechaValutaParameter = p_fechaValuta.HasValue ?
                new ObjectParameter("p_fechaValuta", p_fechaValuta) :
                new ObjectParameter("p_fechaValuta", typeof(System.DateTime));
    
            var p_codBcoCentralParameter = p_codBcoCentral.HasValue ?
                new ObjectParameter("p_codBcoCentral", p_codBcoCentral) :
                new ObjectParameter("p_codBcoCentral", typeof(int));
    
            var p_monto_meParameter = p_monto_me.HasValue ?
                new ObjectParameter("p_monto_me", p_monto_me) :
                new ObjectParameter("p_monto_me", typeof(double));
    
            var p_fechaTransaccionParameter = p_fechaTransaccion.HasValue ?
                new ObjectParameter("p_fechaTransaccion", p_fechaTransaccion) :
                new ObjectParameter("p_fechaTransaccion", typeof(System.DateTime));
    
            var p_tipoCambioPizarraParameter = p_tipoCambioPizarra.HasValue ?
                new ObjectParameter("p_tipoCambioPizarra", p_tipoCambioPizarra) :
                new ObjectParameter("p_tipoCambioPizarra", typeof(double));
    
            var p_tipoTransaccionParameter = p_tipoTransaccion != null ?
                new ObjectParameter("p_tipoTransaccion", p_tipoTransaccion) :
                new ObjectParameter("p_tipoTransaccion", typeof(string));
    
            var p_identificadorConsultaParameter = p_identificadorConsulta != null ?
                new ObjectParameter("p_identificadorConsulta", p_identificadorConsulta) :
                new ObjectParameter("p_identificadorConsulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CrearDealChileFxTesoreria_Result>("CrearDealChileFxTesoreria", p_rutClienteParameter, p_nombreClienteParameter, p_parMoneda1Parameter, p_parMoneda2Parameter, p_precioClienteParameter, p_fechaValutaParameter, p_codBcoCentralParameter, p_monto_meParameter, p_fechaTransaccionParameter, p_tipoCambioPizarraParameter, p_tipoTransaccionParameter, p_identificadorConsultaParameter, ls_folio, ls_msgret, ls_codret);
        }
    
        public virtual int IncorporacionNumeroOperacionSCE(string rutCliente, Nullable<int> numeroDealChileFX, string numeroOperacionSCE, Nullable<decimal> montoSCE, Nullable<decimal> montoChileFX, Nullable<int> codigoEstadoContable, string glosaError, Nullable<bool> exepcionado, Nullable<bool> vbJefatura, ObjectParameter ls_codret, ObjectParameter ls_msgret)
        {
            var rutClienteParameter = rutCliente != null ?
                new ObjectParameter("rutCliente", rutCliente) :
                new ObjectParameter("rutCliente", typeof(string));
    
            var numeroDealChileFXParameter = numeroDealChileFX.HasValue ?
                new ObjectParameter("numeroDealChileFX", numeroDealChileFX) :
                new ObjectParameter("numeroDealChileFX", typeof(int));
    
            var numeroOperacionSCEParameter = numeroOperacionSCE != null ?
                new ObjectParameter("numeroOperacionSCE", numeroOperacionSCE) :
                new ObjectParameter("numeroOperacionSCE", typeof(string));
    
            var montoSCEParameter = montoSCE.HasValue ?
                new ObjectParameter("montoSCE", montoSCE) :
                new ObjectParameter("montoSCE", typeof(decimal));
    
            var montoChileFXParameter = montoChileFX.HasValue ?
                new ObjectParameter("montoChileFX", montoChileFX) :
                new ObjectParameter("montoChileFX", typeof(decimal));
    
            var codigoEstadoContableParameter = codigoEstadoContable.HasValue ?
                new ObjectParameter("codigoEstadoContable", codigoEstadoContable) :
                new ObjectParameter("codigoEstadoContable", typeof(int));
    
            var glosaErrorParameter = glosaError != null ?
                new ObjectParameter("glosaError", glosaError) :
                new ObjectParameter("glosaError", typeof(string));
    
            var exepcionadoParameter = exepcionado.HasValue ?
                new ObjectParameter("exepcionado", exepcionado) :
                new ObjectParameter("exepcionado", typeof(bool));
    
            var vbJefaturaParameter = vbJefatura.HasValue ?
                new ObjectParameter("vbJefatura", vbJefatura) :
                new ObjectParameter("vbJefatura", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IncorporacionNumeroOperacionSCE", rutClienteParameter, numeroDealChileFXParameter, numeroOperacionSCEParameter, montoSCEParameter, montoChileFXParameter, codigoEstadoContableParameter, glosaErrorParameter, exepcionadoParameter, vbJefaturaParameter, ls_codret, ls_msgret);
        }
    
        public virtual ObjectResult<pro_cvd_ni_consulta_precios_Result> pro_cvd_ni_consulta_precios(Nullable<System.DateTime> gb_fecha, string gb_compra_venta, string gb_moneda1, string gb_moneda2, Nullable<decimal> gb_monto_cliente, Nullable<int> gb_rut_cliente, string gb_canal, Nullable<decimal> gb_valor_spread, ObjectParameter ls_codret, ObjectParameter ls_msgret)
        {
            var gb_fechaParameter = gb_fecha.HasValue ?
                new ObjectParameter("gb_fecha", gb_fecha) :
                new ObjectParameter("gb_fecha", typeof(System.DateTime));
    
            var gb_compra_ventaParameter = gb_compra_venta != null ?
                new ObjectParameter("gb_compra_venta", gb_compra_venta) :
                new ObjectParameter("gb_compra_venta", typeof(string));
    
            var gb_moneda1Parameter = gb_moneda1 != null ?
                new ObjectParameter("gb_moneda1", gb_moneda1) :
                new ObjectParameter("gb_moneda1", typeof(string));
    
            var gb_moneda2Parameter = gb_moneda2 != null ?
                new ObjectParameter("gb_moneda2", gb_moneda2) :
                new ObjectParameter("gb_moneda2", typeof(string));
    
            var gb_monto_clienteParameter = gb_monto_cliente.HasValue ?
                new ObjectParameter("gb_monto_cliente", gb_monto_cliente) :
                new ObjectParameter("gb_monto_cliente", typeof(decimal));
    
            var gb_rut_clienteParameter = gb_rut_cliente.HasValue ?
                new ObjectParameter("gb_rut_cliente", gb_rut_cliente) :
                new ObjectParameter("gb_rut_cliente", typeof(int));
    
            var gb_canalParameter = gb_canal != null ?
                new ObjectParameter("gb_canal", gb_canal) :
                new ObjectParameter("gb_canal", typeof(string));
    
            var gb_valor_spreadParameter = gb_valor_spread.HasValue ?
                new ObjectParameter("gb_valor_spread", gb_valor_spread) :
                new ObjectParameter("gb_valor_spread", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_cvd_ni_consulta_precios_Result>("pro_cvd_ni_consulta_precios", gb_fechaParameter, gb_compra_ventaParameter, gb_moneda1Parameter, gb_moneda2Parameter, gb_monto_clienteParameter, gb_rut_clienteParameter, gb_canalParameter, gb_valor_spreadParameter, ls_codret, ls_msgret);
        }
    
        public virtual ObjectResult<pro_cvd_ni_consulta_precios2_Result> pro_cvd_ni_consulta_precios2(Nullable<System.DateTime> gb_fecha, string gb_compra_venta, string gb_moneda1, string gb_moneda2, Nullable<decimal> gb_monto_cliente, Nullable<int> gb_rut_cliente, string gb_canal, string gb_segmento, Nullable<System.DateTime> gb_valuta, ObjectParameter ls_codret, ObjectParameter ls_msgret)
        {
            var gb_fechaParameter = gb_fecha.HasValue ?
                new ObjectParameter("gb_fecha", gb_fecha) :
                new ObjectParameter("gb_fecha", typeof(System.DateTime));
    
            var gb_compra_ventaParameter = gb_compra_venta != null ?
                new ObjectParameter("gb_compra_venta", gb_compra_venta) :
                new ObjectParameter("gb_compra_venta", typeof(string));
    
            var gb_moneda1Parameter = gb_moneda1 != null ?
                new ObjectParameter("gb_moneda1", gb_moneda1) :
                new ObjectParameter("gb_moneda1", typeof(string));
    
            var gb_moneda2Parameter = gb_moneda2 != null ?
                new ObjectParameter("gb_moneda2", gb_moneda2) :
                new ObjectParameter("gb_moneda2", typeof(string));
    
            var gb_monto_clienteParameter = gb_monto_cliente.HasValue ?
                new ObjectParameter("gb_monto_cliente", gb_monto_cliente) :
                new ObjectParameter("gb_monto_cliente", typeof(decimal));
    
            var gb_rut_clienteParameter = gb_rut_cliente.HasValue ?
                new ObjectParameter("gb_rut_cliente", gb_rut_cliente) :
                new ObjectParameter("gb_rut_cliente", typeof(int));
    
            var gb_canalParameter = gb_canal != null ?
                new ObjectParameter("gb_canal", gb_canal) :
                new ObjectParameter("gb_canal", typeof(string));
    
            var gb_segmentoParameter = gb_segmento != null ?
                new ObjectParameter("gb_segmento", gb_segmento) :
                new ObjectParameter("gb_segmento", typeof(string));
    
            var gb_valutaParameter = gb_valuta.HasValue ?
                new ObjectParameter("gb_valuta", gb_valuta) :
                new ObjectParameter("gb_valuta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_cvd_ni_consulta_precios2_Result>("pro_cvd_ni_consulta_precios2", gb_fechaParameter, gb_compra_ventaParameter, gb_moneda1Parameter, gb_moneda2Parameter, gb_monto_clienteParameter, gb_rut_clienteParameter, gb_canalParameter, gb_segmentoParameter, gb_valutaParameter, ls_codret, ls_msgret);
        }
    }
}
