//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Data.DAL.Mcambio
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chilefx_deal_sce
    {
        public long id_chilefx { get; set; }
        public string id_sce { get; set; }
        public decimal mto_chilefx { get; set; }
        public Nullable<decimal> mto_sce { get; set; }
        public System.DateTime fecha_hora_registro { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int codigo_contable { get; set; }
        public string rut_cliente { get; set; }
        public string glosa_error { get; set; }
        public Nullable<bool> exepcionado { get; set; }
        public Nullable<bool> vb_jefatura { get; set; }
        public string codcom { get; set; }
    }
}
