//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/", ConfigurationName="XCFT.ConsultaInformacionBasicaPersona.ConsultaInformacionBasicaPersona")]
    public interface ConsultaInformacionBasicaPersona {
        
        // CODEGEN: Generating message contract since message ConsultarInfoBasicaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/ConsultarInfoBasica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaResponse ConsultarInfoBasica(BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/ConsultarInfoBasica", ReplyAction="*")]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaResponse> ConsultarInfoBasicaAsync(BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosHeaderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosConsumidor consumidorField;
        
        private datosTransaccion transaccionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosConsumidor consumidor {
            get {
                return this.consumidorField;
            }
            set {
                this.consumidorField = value;
                this.RaisePropertyChanged("consumidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public datosTransaccion transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosConsumidor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idAppField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idApp {
            get {
                return this.idAppField;
            }
            set {
                this.idAppField = value;
                this.RaisePropertyChanged("idApp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="datosTransaccion", Namespace="http://osb.bancochile.cl/common/HeaderResponse")]
    public partial class datosTransaccion1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.Nullable<System.DateTime> fechaHoraInicioTrxField;
        
        private System.Nullable<System.DateTime> fechaHoraFinTrxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> fechaHoraInicioTrx {
            get {
                return this.fechaHoraInicioTrxField;
            }
            set {
                this.fechaHoraInicioTrxField = value;
                this.RaisePropertyChanged("fechaHoraInicioTrx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fechaHoraFinTrx {
            get {
                return this.fechaHoraFinTrxField;
            }
            set {
                this.fechaHoraFinTrxField = value;
                this.RaisePropertyChanged("fechaHoraFinTrx");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderResponse")]
    public partial class datosHeaderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosTransaccion1 transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosTransaccion1 transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosTransaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaHoraField;
        
        private string canalField;
        
        private string sucursalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("sucursal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/entities/contactabilidad/Telefono")]
    public partial class telefono : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codPaisField;
        
        private string codAreaField;
        
        private string numeroField;
        
        private string anexoField;
        
        private string tipoTelefonoField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
                this.RaisePropertyChanged("codPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codArea {
            get {
                return this.codAreaField;
            }
            set {
                this.codAreaField = value;
                this.RaisePropertyChanged("codArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string anexo {
            get {
                return this.anexoField;
            }
            set {
                this.anexoField = value;
                this.RaisePropertyChanged("anexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tipoTelefono {
            get {
                return this.tipoTelefonoField;
            }
            set {
                this.tipoTelefonoField = value;
                this.RaisePropertyChanged("tipoTelefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ConsultaInformacionBasicaPersona/OpConsultarInfoBasi" +
        "caResponse")]
    public partial class datosTelefono : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rowIdTelefonoField;
        
        private System.Nullable<System.DateTime> fechaActualizacionField;
        
        private telefono telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rowIdTelefono {
            get {
                return this.rowIdTelefonoField;
            }
            set {
                this.rowIdTelefonoField = value;
                this.RaisePropertyChanged("rowIdTelefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public telefono telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/entities/contactabilidad/DatosEjecutivo")]
    public partial class DatosEjecutivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paternoField;
        
        private string maternoField;
        
        private string nombresField;
        
        private string codPositionField;
        
        private string oficinaField;
        
        private string emailField;
        
        private string primarioField;
        
        private string cargoField;
        
        private string telefonoField;
        
        private string faxField;
        
        private string anexoField;
        
        private string tipoEjecutivoField;
        
        private string positionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                this.paternoField = value;
                this.RaisePropertyChanged("paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                this.maternoField = value;
                this.RaisePropertyChanged("materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string codPosition {
            get {
                return this.codPositionField;
            }
            set {
                this.codPositionField = value;
                this.RaisePropertyChanged("codPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string oficina {
            get {
                return this.oficinaField;
            }
            set {
                this.oficinaField = value;
                this.RaisePropertyChanged("oficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string primario {
            get {
                return this.primarioField;
            }
            set {
                this.primarioField = value;
                this.RaisePropertyChanged("primario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string anexo {
            get {
                return this.anexoField;
            }
            set {
                this.anexoField = value;
                this.RaisePropertyChanged("anexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string tipoEjecutivo {
            get {
                return this.tipoEjecutivoField;
            }
            set {
                this.tipoEjecutivoField = value;
                this.RaisePropertyChanged("tipoEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string positionId {
            get {
                return this.positionIdField;
            }
            set {
                this.positionIdField = value;
                this.RaisePropertyChanged("positionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/entities/contactabilidad/Direccion")]
    public partial class direccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rowIdDirField;
        
        private string direccion1Field;
        
        private string numeroField;
        
        private string departamentoField;
        
        private string regionField;
        
        private string ciudadField;
        
        private string comunaField;
        
        private string tipoDireccionField;
        
        private string codigoPostalField;
        
        private string tipoDespachoField;
        
        private System.Nullable<System.DateTime> fechaActualizacionField;
        
        private string verificadaPorField;
        
        private System.Nullable<System.DateTime> fechaVerificacionField;
        
        private string veriVisadaField;
        
        private string veriEmpExtField;
        
        private string usoLegalField;
        
        private string usoPostalField;
        
        private string normalizadaField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rowIdDir {
            get {
                return this.rowIdDirField;
            }
            set {
                this.rowIdDirField = value;
                this.RaisePropertyChanged("rowIdDir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("direccion", Order=1)]
        public string direccion1 {
            get {
                return this.direccion1Field;
            }
            set {
                this.direccion1Field = value;
                this.RaisePropertyChanged("direccion1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("comuna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string tipoDireccion {
            get {
                return this.tipoDireccionField;
            }
            set {
                this.tipoDireccionField = value;
                this.RaisePropertyChanged("tipoDireccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
                this.RaisePropertyChanged("codigoPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string tipoDespacho {
            get {
                return this.tipoDespachoField;
            }
            set {
                this.tipoDespachoField = value;
                this.RaisePropertyChanged("tipoDespacho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string verificadaPor {
            get {
                return this.verificadaPorField;
            }
            set {
                this.verificadaPorField = value;
                this.RaisePropertyChanged("verificadaPor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> fechaVerificacion {
            get {
                return this.fechaVerificacionField;
            }
            set {
                this.fechaVerificacionField = value;
                this.RaisePropertyChanged("fechaVerificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string veriVisada {
            get {
                return this.veriVisadaField;
            }
            set {
                this.veriVisadaField = value;
                this.RaisePropertyChanged("veriVisada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string veriEmpExt {
            get {
                return this.veriEmpExtField;
            }
            set {
                this.veriEmpExtField = value;
                this.RaisePropertyChanged("veriEmpExt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string usoLegal {
            get {
                return this.usoLegalField;
            }
            set {
                this.usoLegalField = value;
                this.RaisePropertyChanged("usoLegal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string usoPostal {
            get {
                return this.usoPostalField;
            }
            set {
                this.usoPostalField = value;
                this.RaisePropertyChanged("usoPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string normalizada {
            get {
                return this.normalizadaField;
            }
            set {
                this.normalizadaField = value;
                this.RaisePropertyChanged("normalizada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/entities/contactabilidad/Email")]
    public partial class correo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string tipoEmailField;
        
        private System.Nullable<System.DateTime> fechaActualizacionField;
        
        private string usoPostalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tipoEmail {
            get {
                return this.tipoEmailField;
            }
            set {
                this.tipoEmailField = value;
                this.RaisePropertyChanged("tipoEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usoPostal {
            get {
                return this.usoPostalField;
            }
            set {
                this.usoPostalField = value;
                this.RaisePropertyChanged("usoPostal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ConsultaInformacionBasicaPersona/OpConsultarInfoBasi" +
        "caResponse")]
    public partial class datosCorreo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rowIdEmailField;
        
        private correo emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rowIdEmail {
            get {
                return this.rowIdEmailField;
            }
            set {
                this.rowIdEmailField = value;
                this.RaisePropertyChanged("rowIdEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public correo email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ConsultaInformacionBasicaPersona/OpConsultarInfoBasi" +
        "caResponse")]
    public partial class detalleAmbito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ambitoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ambito {
            get {
                return this.ambitoField;
            }
            set {
                this.ambitoField = value;
                this.RaisePropertyChanged("ambito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ConsultaInformacionBasicaPersona/OpConsultarInfoBasi" +
        "caResponse")]
    public partial class datosSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string cargoField;
        
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        private string flagEnviaCorreoField;
        
        private string nombresField;
        
        private string razonSocialField;
        
        private detalleAmbito[] listaAmbitosField;
        
        private datosCorreo[] listaCorreosField;
        
        private direccion[] listaDireccionesField;
        
        private DatosEjecutivo[] listaEjecutivosField;
        
        private datosTelefono[] listaTelefonosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string flagEnviaCorreo {
            get {
                return this.flagEnviaCorreoField;
            }
            set {
                this.flagEnviaCorreoField = value;
                this.RaisePropertyChanged("flagEnviaCorreo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public detalleAmbito[] listaAmbitos {
            get {
                return this.listaAmbitosField;
            }
            set {
                this.listaAmbitosField = value;
                this.RaisePropertyChanged("listaAmbitos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("correo")]
        public datosCorreo[] listaCorreos {
            get {
                return this.listaCorreosField;
            }
            set {
                this.listaCorreosField = value;
                this.RaisePropertyChanged("listaCorreos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("direcciones")]
        public direccion[] listaDirecciones {
            get {
                return this.listaDireccionesField;
            }
            set {
                this.listaDireccionesField = value;
                this.RaisePropertyChanged("listaDirecciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ejecutivos")]
        public DatosEjecutivo[] listaEjecutivos {
            get {
                return this.listaEjecutivosField;
            }
            set {
                this.listaEjecutivosField = value;
                this.RaisePropertyChanged("listaEjecutivos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("telefono")]
        public datosTelefono[] listaTelefonos {
            get {
                return this.listaTelefonosField;
            }
            set {
                this.listaTelefonosField = value;
                this.RaisePropertyChanged("listaTelefonos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ConsultaInformacionBasicaPersona/OpConsultarInfoBasi" +
        "caRequest")]
    public partial class datosEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutPersonaField;
        
        private string rutEmpresaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rutPersona {
            get {
                return this.rutPersonaField;
            }
            set {
                this.rutPersonaField = value;
                this.RaisePropertyChanged("rutPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string rutEmpresa {
            get {
                return this.rutEmpresaField;
            }
            set {
                this.rutEmpresaField = value;
                this.RaisePropertyChanged("rutEmpresa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarInfoBasica", WrapperNamespace="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/", IsWrapped=true)]
    public partial class ConsultarInfoBasicaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/")]
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosHeaderRequest headerRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosEntrada datosEntrada;
        
        public ConsultarInfoBasicaRequest() {
        }
        
        public ConsultarInfoBasicaRequest(BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosEntrada datosEntrada) {
            this.headerRequest = headerRequest;
            this.datosEntrada = datosEntrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarInfoBasicaResponse", WrapperNamespace="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/", IsWrapped=true)]
    public partial class ConsultarInfoBasicaResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/")]
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosHeaderResponse headerResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/ConsultaInformacionBasicaPersona/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosSalida datosSalida;
        
        public ConsultarInfoBasicaResponse() {
        }
        
        public ConsultarInfoBasicaResponse(BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosHeaderResponse headerResponse, BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosSalida datosSalida) {
            this.headerResponse = headerResponse;
            this.datosSalida = datosSalida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaInformacionBasicaPersonaChannel : BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultaInformacionBasicaPersona, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaInformacionBasicaPersonaClient : System.ServiceModel.ClientBase<BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultaInformacionBasicaPersona>, BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultaInformacionBasicaPersona {
        
        public ConsultaInformacionBasicaPersonaClient() {
        }
        
        public ConsultaInformacionBasicaPersonaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaInformacionBasicaPersonaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaInformacionBasicaPersonaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaInformacionBasicaPersonaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaResponse BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultaInformacionBasicaPersona.ConsultarInfoBasica(BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaRequest request) {
            return base.Channel.ConsultarInfoBasica(request);
        }
        
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosHeaderResponse ConsultarInfoBasica(BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosEntrada datosEntrada, out BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosSalida datosSalida) {
            BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaRequest inValue = new BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaRequest();
            inValue.headerRequest = headerRequest;
            inValue.datosEntrada = datosEntrada;
            BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaResponse retVal = ((BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultaInformacionBasicaPersona)(this)).ConsultarInfoBasica(inValue);
            datosSalida = retVal.datosSalida;
            return retVal.headerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaResponse> BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaAsync(BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaRequest request) {
            return base.Channel.ConsultarInfoBasicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaResponse> ConsultarInfoBasicaAsync(BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.datosEntrada datosEntrada) {
            BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaRequest inValue = new BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultarInfoBasicaRequest();
            inValue.headerRequest = headerRequest;
            inValue.datosEntrada = datosEntrada;
            return ((BCH.Comex.Data.DAL.Services.XCFT.ConsultaInformacionBasicaPersona.ConsultaInformacionBasicaPersona)(this)).ConsultarInfoBasicaAsync(inValue);
        }
    }
}
