//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.swift
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_firmas_msg
    {
        public int sesion_firma { get; set; }
        public int secuencia_firma { get; set; }
        public string send_recv_firma { get; set; }
        public int rut_firma { get; set; }
    }
}
