//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.swift
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_msgsend_log
    {
        public int id_mensaje { get; set; }
        public System.DateTime fecha_log { get; set; }
        public Nullable<int> rutais_log { get; set; }
        public string nodoais_log { get; set; }
        public string idprog_log { get; set; }
        public string opcion_log { get; set; }
        public Nullable<int> casilla_origen { get; set; }
        public string estado_origen { get; set; }
        public Nullable<int> casilla_destino { get; set; }
        public string estado_destino { get; set; }
        public Nullable<int> unidad_log { get; set; }
        public string resultado_log { get; set; }
        public string comentario_log { get; set; }
    }
}
