//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.swift
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_msgsend_cambio_estados
    {
        public int id_mensaje { get; set; }
        public string estado_msg { get; set; }
        public System.DateTime fecha_estado { get; set; }
    }
}
