//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.swift
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_mensajes
    {
        public int sesion { get; set; }
        public int secuencia { get; set; }
        public string send_recv { get; set; }
        public int casilla { get; set; }
        public Nullable<int> unidad { get; set; }
        public string tipo_msg { get; set; }
        public string prioridad { get; set; }
        public string estado_msg { get; set; }
        public Nullable<int> rut_entry { get; set; }
        public Nullable<int> rut_autoriza { get; set; }
        public Nullable<System.DateTime> fecha_send { get; set; }
        public Nullable<System.DateTime> fecha_ack { get; set; }
        public string cod_banco_rec { get; set; }
        public string branch_rec { get; set; }
        public string cod_banco_em { get; set; }
        public string branch_em { get; set; }
        public string cod_moneda { get; set; }
        public Nullable<double> monto { get; set; }
        public string referencia { get; set; }
        public string beneficiario { get; set; }
        public Nullable<int> total_imp { get; set; }
        public string mensaje { get; set; }
        public string comentario { get; set; }
    }
}
