//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.swift
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_tipos_firmas
    {
        public string codig_rh { get; set; }
        public string tipofirma { get; set; }
    }
}
