//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_nyc
    {
        public string nyc_codswi { get; set; }
        public string nyc_cuenta { get; set; }
        public int nyc_codpai { get; set; }
        public string nyc_ciudad { get; set; }
        public int nyc_codmnd { get; set; }
        public string nyc_chqemi { get; set; }
        public int nyc_estado { get; set; }
        public string nyc_corresp { get; set; }
        public int nyc_tipocta { get; set; }
        public System.DateTime nyc_fecape { get; set; }
        public int nyc_codbde { get; set; }
        public int nyc_ruting { get; set; }
        public string nyc_dving { get; set; }
        public System.DateTime nyc_fecing { get; set; }
        public int nyc_rutact { get; set; }
        public string nyc_dvact { get; set; }
        public System.DateTime nyc_fecact { get; set; }
    }
}
