//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_linr
    {
        public string linr_codswi { get; set; }
        public int linr_codpai { get; set; }
        public int linr_codmnd { get; set; }
        public double linr_mtolinr { get; set; }
        public double linr_mtolino { get; set; }
        public double linr_mtolind { get; set; }
        public double linr_ruting { get; set; }
        public string linr_dving { get; set; }
        public System.DateTime linr_fecing { get; set; }
        public double linr_rutact { get; set; }
        public string linr_dvact { get; set; }
        public System.DateTime linr_fecact { get; set; }
        public string linr_proceso { get; set; }
        public int linr_rnkbco { get; set; }
        public string linr_descrip { get; set; }
        public string linr_tippar { get; set; }
        public string linr_swfcto { get; set; }
        public int linr_codcto { get; set; }
    
        public virtual sbc_bco sbc_bco { get; set; }
    }
}
