//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_recf
    {
        public int recf_periodo { get; set; }
        public int recf_codpai { get; set; }
        public string recf_famswi { get; set; }
        public string recf_codope { get; set; }
        public string recf_codofi { get; set; }
        public int recf_codmnd { get; set; }
        public int recf_volopep { get; set; }
        public double recf_mtoopep { get; set; }
        public int recf_volopea { get; set; }
        public double recf_mtoopea { get; set; }
        public int recf_voloprp { get; set; }
        public double recf_mtooprp { get; set; }
        public int recf_volopra { get; set; }
        public double recf_mtoopra { get; set; }
        public int recf_volbalp { get; set; }
        public double recf_mtobalp { get; set; }
        public int recf_volbala { get; set; }
        public double recf_mtobala { get; set; }
    
        public virtual sbc_ofi sbc_ofi { get; set; }
        public virtual sbc_ope sbc_ope { get; set; }
        public virtual sgt_pai sgt_pai { get; set; }
    }
}
