//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{
    using System;

    public partial class sbc_rstd
    {
        public int rstd_codgru { get; set; }
        public int rstd_codrst { get; set; }
        public int rstd_codpai { get; set; }
        public Nullable<double> rstd_mtoval { get; set; }
        public Nullable<double> rstd_mtoreal { get; set; }
        public Nullable<int> rstd_codmnd { get; set; }
    }
}
