//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_bere
    {
        public string bere_codswi { get; set; }
        public int bere_agno { get; set; }
        public int bere_codpai { get; set; }
        public int bere_mes { get; set; }
        public System.DateTime bere_feccta { get; set; }
        public System.DateTime bere_fecing { get; set; }
        public string bere_audita { get; set; }
        public int bere_codmnd { get; set; }
        public string bere_nemmnd { get; set; }
        public double bere_paridad { get; set; }
        public double bere_nummes { get; set; }
        public double bere_indmto { get; set; }
        public string bere_obsber { get; set; }
    }
}
