//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_linp_ope
    {
        public string ope_codlin { get; set; }
        public string ope_codlint { get; set; }
        public string ope_codope { get; set; }
        public int ope_codlinc { get; set; }
    }
}
