//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_crp
    {
        public string crp_tp_reg { get; set; }
        public string crp_rut { get; set; }
        public string crp_dv { get; set; }
        public string crp_suc_ptmo { get; set; }
        public string crp_num_ptmo { get; set; }
        public string crp_rut_emp { get; set; }
        public string crp_dv_emp { get; set; }
        public string crp_moneda { get; set; }
        public string crp_monto_vigente { get; set; }
        public string crp_fecha_inicio { get; set; }
        public string crp_fecha_vencimiento { get; set; }
        public string crp_tipo_tasa { get; set; }
        public string crp_tasa_base { get; set; }
        public string crp_signo_spread { get; set; }
        public string crp_spread { get; set; }
        public string crp_tasa_total { get; set; }
        public string crp_to { get; set; }
        public string crp_oficina { get; set; }
        public string crp_cod_ejec { get; set; }
        public string crp_filler { get; set; }
        public string crp_operie { get; set; }
        public string crp_clainv { get; set; }
    }
}
