//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{
    using System;

    public partial class sbc_datos_superiores_mod
    {
        public int mbd_codpai { get; set; }
        public string mbd_codswi { get; set; }
        public string mbd_codlint { get; set; }
        public int mbd_codlinc { get; set; }
        public string mbd_codlin { get; set; }
        public Nullable<System.DateTime> mbr_fecven { get; set; }
        public Nullable<double> mbr_mtomac { get; set; }
        public Nullable<int> rut_mod { get; set; }
        public string dv_mod { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_pantalla { get; set; }
        public Nullable<int> modifica_fec { get; set; }
        public Nullable<int> modifica_mto { get; set; }
        public string mpr_codlin { get; set; }
        public string mpr_clasinv { get; set; }
        public string mpr_tiplin { get; set; }
        public Nullable<System.DateTime> mpr_fecapr { get; set; }
        public Nullable<System.DateTime> mpr_fecven { get; set; }
        public Nullable<int> modifica_linea { get; set; }
        public Nullable<int> modifica_clasi { get; set; }
        public Nullable<int> modifica_fec_aper { get; set; }
    }
}
