//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{
    using System;

    public partial class sbc_lin
    {
        public string lin_codlin { get; set; }
        public decimal lin_prcptr { get; set; }
        public double lin_mtomax { get; set; }
        public int lin_codmnd { get; set; }
        public Nullable<decimal> lin_prcprv { get; set; }
    }
}
