//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_tyc1
    {
        public int tyc1_nrocor { get; set; }
        public string tyc1_estado { get; set; }
        public string tyc1_codswi { get; set; }
        public string tyc1_nombco { get; set; }
        public string tyc1_contacto { get; set; }
        public int tyc1_codpai { get; set; }
        public string tyc1_ciudad { get; set; }
        public int tyc1_codpro { get; set; }
        public string tyc1_tipcom { get; set; }
        public string tyc1_tipcome { get; set; }
        public string tyc1_numref { get; set; }
        public string tyc1_refsec { get; set; }
        public string tyc1_idimport { get; set; }
        public string tyc1_idexport { get; set; }
        public string tyc1_nomimport { get; set; }
        public string tyc1_nomexport { get; set; }
        public string tyc1_fpago { get; set; }
        public string tyc1_letras { get; set; }
        public string tyc1_gastos { get; set; }
        public int tyc1_validez { get; set; }
        public int tyc1_mndope { get; set; }
        public double tyc1_mtoope { get; set; }
        public double tyc1_parope { get; set; }
        public double tyc1_mtooped { get; set; }
        public int tyc1_codmnd { get; set; }
        public double tyc1_prcall { get; set; }
        public double tyc1_valmin { get; set; }
        public double tyc1_valpar { get; set; }
        public System.DateTime tyc1_fecpar { get; set; }
        public double tyc1_valmind { get; set; }
        public string tyc1_codcct { get; set; }
        public string tyc1_codesp { get; set; }
        public System.DateTime tyc1_fecing { get; set; }
        public System.DateTime tyc1_feccot { get; set; }
        public int tyc1_ruteje { get; set; }
        public string tyc1_dveje { get; set; }
        public System.DateTime tyc1_fecres { get; set; }
        public string tyc1_observ { get; set; }
        public string tyc1_obsesp { get; set; }
        public string tyc1_nomesp { get; set; }
        public string tyc1_fonoesp { get; set; }
        public string tyc1_tipocci { get; set; }
        public int tyc1_rutcot { get; set; }
        public string tyc1_dvcot { get; set; }
    }
}
