//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{
    using System;

    public partial class sbc_pex
    {
        public string pex_swift { get; set; }
        public string pex_codope { get; set; }
        public string pex_numref { get; set; }
        public Nullable<int> pex_estado { get; set; }
        public string pex_ofiori { get; set; }
        public Nullable<int> pex_codmnd { get; set; }
        public Nullable<double> pex_mtoope { get; set; }
        public Nullable<System.DateTime> pex_fecini { get; set; }
        public Nullable<System.DateTime> pex_fecven { get; set; }
        public string pex_tiptas { get; set; }
        public Nullable<double> pex_tasa { get; set; }
        public Nullable<double> pex_spread { get; set; }
        public Nullable<double> pex_tastot { get; set; }
        public string pex_codsubl { get; set; }
        public string pex_plazo { get; set; }
    }
}
