//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_ctrl
    {
        public string ctrl_codswi { get; set; }
        public int ctrl_numcor { get; set; }
        public string ctrl_grupo { get; set; }
        public double ctrl_prcgrp { get; set; }
    
        public virtual sbc_bco sbc_bco { get; set; }
    }
}
