//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_tycc
    {
        public string tycc_codswi { get; set; }
        public int tycc_codgru { get; set; }
        public int tycc_codpro { get; set; }
        public int tycc_codcom { get; set; }
        public int tycc_codmnd { get; set; }
        public double tycc_prccom { get; set; }
        public double tycc_valmin { get; set; }
        public int tycc_nveces { get; set; }
        public double tycc_mtoadi { get; set; }
        public int tycc_dias { get; set; }
        public int tycc_period { get; set; }
        public double tycc_valpar { get; set; }
        public System.DateTime tycc_fecpar { get; set; }
        public double tycc_valmind { get; set; }
        public string tycc_observ { get; set; }
    }
}
