//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{
    using System;

    public partial class sbc_mbr
    {
        public string mbr_codswi { get; set; }
        public string mbr_codlin { get; set; }
        public int mbr_codpai { get; set; }
        public System.DateTime mbr_fecapr { get; set; }
        public System.DateTime mbr_fecven { get; set; }
        public Nullable<int> mbr_estado { get; set; }
        public int mbr_codmnd { get; set; }
        public double mbr_mtomac { get; set; }
        public double mbr_mtoout { get; set; }
        public double mbr_mtodis { get; set; }
        public int mbr_ruting { get; set; }
        public string mbr_dving { get; set; }
        public System.DateTime mbr_fecing { get; set; }
        public int mbr_rutmod { get; set; }
        public string mbr_dvmod { get; set; }
        public System.DateTime mbr_fecmod { get; set; }
        public string mbr_tiplin { get; set; }
        public Nullable<int> mbr_estadovi { get; set; }
        public Nullable<System.DateTime> mbr_fecha_visado { get; set; }
        public Nullable<int> mbr_rutauto { get; set; }
        public string mbr_dvauto { get; set; }
    }
}
