//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_lre
    {
        public int lre_key { get; set; }
        public string lre_codsis { get; set; }
        public string lre_tiplre { get; set; }
        public string lre_codope { get; set; }
        public string lre_nomope { get; set; }
        public string lre_numref { get; set; }
        public string lre_tipsubl { get; set; }
        public string lre_plazo { get; set; }
        public System.DateTime lre_fecpro { get; set; }
        public string lre_codofi { get; set; }
        public string lre_codswi { get; set; }
        public string lre_nombco { get; set; }
        public int lre_rutemp { get; set; }
        public string lre_dvemp { get; set; }
        public string lre_nomemp { get; set; }
        public System.DateTime lre_fecini { get; set; }
        public System.DateTime lre_fecven { get; set; }
        public int lre_codmnd { get; set; }
        public double lre_mtoope { get; set; }
        public double lre_tasa { get; set; }
        public double lre_spread { get; set; }
        public int lre_estado { get; set; }
        public int lre_coderr { get; set; }
        public string lre_swioper { get; set; }
        public string lre_nomswop { get; set; }
        public int lre_paioper { get; set; }
        public string lre_nompaiop { get; set; }
        public string lre_obslot { get; set; }
    }
}
