//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_lotasg
    {
        public string lotasg_codope { get; set; }
        public string lotasg_numref { get; set; }
        public string lotasg_refsec { get; set; }
        public string lotasg_codofi { get; set; }
        public string lotasg_tiplot { get; set; }
        public int lotasg_codpai { get; set; }
        public string lotasg_nompai { get; set; }
        public string lotasg_codswi { get; set; }
        public string lotasg_rutemp { get; set; }
        public string lotasg_nombre { get; set; }
        public string lotasg_smart { get; set; }
        public string lotasg_matriz { get; set; }
    }
}
