//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_bcoi
    {
        public string bcoi_codswi { get; set; }
        public string bcoi_codpai { get; set; }
        public string bcoi_tipbco { get; set; }
        public string bcoi_swimat { get; set; }
        public string bcoi_paimat { get; set; }
        public string bcoi_rutbco { get; set; }
        public string bcoi_dvbco { get; set; }
        public string bcoi_rutsuper { get; set; }
        public string bcoi_dvsuper { get; set; }
        public string bcoi_codbde { get; set; }
        public string bcoi_nombre { get; set; }
        public string bcoi_direccion { get; set; }
        public string bcoi_ciudad { get; set; }
        public string bcoi_cpostal { get; set; }
        public string bcoi_pais { get; set; }
        public string bcoi_corresp { get; set; }
        public string bcoi_deudor { get; set; }
        public string bcoi_acreedor { get; set; }
        public string bcoi_rnkpai { get; set; }
        public string bcoi_rnkmun { get; set; }
        public string bcoi_clfbco { get; set; }
        public string bcoi_catbcoa { get; set; }
        public string bcoi_catbcom { get; set; }
    }
}
