//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbc_hope
    {
        public System.DateTime hope_fecha { get; set; }
        public int hope_cod { get; set; }
        public string hope_tiperr { get; set; }
        public string hope_tipsis { get; set; }
        public string hope_codope { get; set; }
        public string hope_custid { get; set; }
        public string hope_errdes { get; set; }
        public string hope_nomemp { get; set; }
        public System.DateTime hope_fecini { get; set; }
        public System.DateTime hope_fecven { get; set; }
        public string hope_swimnd { get; set; }
        public double hope_mtoope { get; set; }
        public string hope_refope { get; set; }
        public string hope_oficin { get; set; }
        public string hope_nompai { get; set; }
        public string hope_rutswi { get; set; }
        public string hope_tipope { get; set; }
    }
}
