//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{

    public partial class sbcsitf
    {
        public string sitf_codswi { get; set; }
        public System.DateTime sitf_fecsit { get; set; }
        public int sitf_codpai { get; set; }
        public int sitf_codmnd { get; set; }
        public double sitf_mtoact { get; set; }
        public double sitf_mtocol { get; set; }
        public double sitf_mtodep { get; set; }
        public double sitf_mtopat { get; set; }
        public double sitf_mtouti { get; set; }
        public double sitf_lvr { get; set; }
        public double sitf_roa { get; set; }
        public double sitf_roe { get; set; }
        public double sitf_bis { get; set; }
    }
}
