//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{
    using System;

    public partial class sgt_tba
    {
        public decimal tba_cod { get; set; }
        public string tba_nom { get; set; }
        public decimal tba_cpa { get; set; }
        public string tba_rut { get; set; }
        public string tba_fap { get; set; }
        public string tba_fci { get; set; }
        public string tba_csw { get; set; }
        public decimal tba_rnk { get; set; }
        public string tba_frk { get; set; }
        public Nullable<decimal> tba_cat { get; set; }
        public string tba_cal { get; set; }
    }
}
