//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Sbcor
{
    using System.Collections.Generic;
    
    public partial class sgt_pai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sgt_pai()
        {
            this.sbc_recf = new HashSet<sbc_recf>();
            this.sbc_reco = new HashSet<sbc_reco>();
        }
    
        public int pai_paicod { get; set; }
        public string pai_painom { get; set; }
        public string pai_paiala { get; set; }
        public string pai_noming { get; set; }
        public string pai_paiabr { get; set; }
    
        public virtual sbc_macp sbc_macp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbc_recf> sbc_recf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbc_reco> sbc_reco { get; set; }
    }
}
