//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_pro
    {
        public int pro_periodo { get; set; }
        public string pro_codtab { get; set; }
        public int pro_regtot { get; set; }
        public int pro_regpro { get; set; }
        public int pro_regok { get; set; }
        public int pro_regerr { get; set; }
        public double pro_mtopro { get; set; }
        public double pro_mtook { get; set; }
        public double pro_mtoerr { get; set; }
        public int pro_coderr { get; set; }
    
        public virtual sbc_err sbc_err { get; set; }
    }
}
