//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_exd
    {
        public int exd_key { get; set; }
        public string exd_tiplot { get; set; }
        public string exd_codope { get; set; }
        public string exd_nomope { get; set; }
        public string exd_numref { get; set; }
        public string exd_codofi { get; set; }
        public int exd_codpai { get; set; }
        public string exd_codswi { get; set; }
        public string exd_rutemp { get; set; }
        public int exd_numrut { get; set; }
        public string exd_dvemp { get; set; }
        public string exd_nombre { get; set; }
        public System.DateTime exd_fecini { get; set; }
        public System.DateTime exd_fecven { get; set; }
        public int exd_codmnd { get; set; }
        public double exd_mtoope { get; set; }
        public double exd_paridad { get; set; }
        public double exd_mtodol { get; set; }
        public int exd_estado { get; set; }
        public int exd_coderr { get; set; }
        public string exd_nomerr { get; set; }
        public string exd_tipotrn { get; set; }
        public string exd_plazo { get; set; }
        public double exd_spread { get; set; }
    }
}
