//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_prvcus
    {
        public string prv_fecprv { get; set; }
        public string prv_codofi { get; set; }
        public string prv_custidn { get; set; }
        public string prv_custnum { get; set; }
        public string prv_clasrie { get; set; }
        public string prv_custnam { get; set; }
        public double prv_mtocap { get; set; }
        public double prv_mtoint { get; set; }
        public double prv_mtocon { get; set; }
        public double prv_mtotot { get; set; }
        public double prv_prvclf { get; set; }
        public double prv_prvcar { get; set; }
    }
}
