//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_sitf
    {
        public string sitf_codswi { get; set; }
        public System.DateTime sitf_fecsit { get; set; }
        public int sitf_codpai { get; set; }
        public int sitf_codmnd { get; set; }
        public double sitf_indmto { get; set; }
        public double sitf_mtoact { get; set; }
        public double sitf_mtoactr { get; set; }
        public double sitf_mtocol { get; set; }
        public double sitf_mtocolr { get; set; }
        public double sitf_mtodep { get; set; }
        public double sitf_mtodepr { get; set; }
        public double sitf_mtopat { get; set; }
        public double sitf_mtopatr { get; set; }
        public double sitf_mtouti { get; set; }
        public double sitf_mtoutir { get; set; }
        public double sitf_lvr { get; set; }
        public double sitf_roa { get; set; }
        public double sitf_roe { get; set; }
        public double sitf_bis { get; set; }
    
        public virtual sbc_bco sbc_bco { get; set; }
    }
}
