//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_mpr
    {
        public int mpr_codpai { get; set; }
        public string mpr_codlin { get; set; }
        public System.DateTime mpr_fecapr { get; set; }
        public System.DateTime mpr_fecven { get; set; }
        public Nullable<int> mpr_estado { get; set; }
        public int mpr_codmnd { get; set; }
        public double mpr_mtomac { get; set; }
        public double mpr_mtoout { get; set; }
        public double mpr_mtodis { get; set; }
        public int mpr_ruting { get; set; }
        public string mpr_dving { get; set; }
        public System.DateTime mpr_fecing { get; set; }
        public int mpr_rutmod { get; set; }
        public string mpr_dvmod { get; set; }
        public System.DateTime mpr_fecmod { get; set; }
        public string mpr_clasinv { get; set; }
        public Nullable<int> mpr_estadovi { get; set; }
        public Nullable<System.DateTime> mpr_fecha_visado { get; set; }
        public Nullable<int> mpr_rutauto { get; set; }
        public string mpr_dvauto { get; set; }
    }
}
