//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_rutsw
    {
        public int rutsw_numrut { get; set; }
        public string rutsw_digv { get; set; }
        public string rutsw_codswi { get; set; }
        public string rutsw_trncrp { get; set; }
    }
}
