//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_lot
    {
        public int lot_key { get; set; }
        public string lot_tiplot { get; set; }
        public string lot_codope { get; set; }
        public string lot_numref { get; set; }
        public string lot_refsec { get; set; }
        public System.DateTime lot_fecpro { get; set; }
        public string lot_codofi { get; set; }
        public int lot_codpai { get; set; }
        public string lot_codswi { get; set; }
        public string lot_rutemp { get; set; }
        public int lot_numrut { get; set; }
        public string lot_dvemp { get; set; }
        public System.DateTime lot_fecini { get; set; }
        public System.DateTime lot_fecven { get; set; }
        public int lot_codmnd { get; set; }
        public double lot_mtoori { get; set; }
        public double lot_mtoope { get; set; }
        public int lot_estado { get; set; }
        public int lot_coderr { get; set; }
        public int lot_congar { get; set; }
        public string lot_swimat { get; set; }
        public int lot_paimat { get; set; }
        public int lot_paigar { get; set; }
        public int lot_prccom { get; set; }
        public int lot_prcpai { get; set; }
        public double lot_mtocom { get; set; }
        public double lot_mtopai { get; set; }
        public string lot_obslot { get; set; }
        public string lot_nomope { get; set; }
        public string lot_nombre { get; set; }
        public int lot_pairsg { get; set; }
        public string lot_tipotrn { get; set; }
        public string lot_sublim { get; set; }
        public string lot_plazo { get; set; }
        public string lot_paigar_ { get; set; }
        public double lot_tasa { get; set; }
        public double lot_spread { get; set; }
        public double lot_tasat { get; set; }
        public string lot_tenor { get; set; }
        public bool lot_conprv { get; set; }
        public int lot_paiprv { get; set; }
        public int lot_codgru { get; set; }
        public double lot_prcgru { get; set; }
        public double lot_mtoprv { get; set; }
        public string lot_obsprv { get; set; }
        public string lot_codpai_ { get; set; }
        public string lot_paiprv_ { get; set; }
        public System.DateTime lot_fecori { get; set; }
        public string lot_custid { get; set; }
        public string lot_operie { get; set; }
        public string lot_clainv { get; set; }
        public Nullable<int> lot_estrie { get; set; }
        public Nullable<int> lot_errrie { get; set; }
        public Nullable<int> lot_codlinc { get; set; }
        public string lot_nomsec { get; set; }
    
        public virtual sbc_err sbc_err { get; set; }
    }
}
