//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_hdetpai
    {
        public System.DateTime pai_fecha { get; set; }
        public int pai_cod { get; set; }
        public int pai_codpai { get; set; }
        public string pai_painom { get; set; }
        public double pai_mtomac { get; set; }
        public double pai_mtoout { get; set; }
        public double pai_mtodis { get; set; }
        public double bco_mtomac { get; set; }
        public double bco_mtoout { get; set; }
        public double bco_mtodis { get; set; }
        public double det_mtomac { get; set; }
        public double det_mtoout { get; set; }
        public double det_mtodis { get; set; }
        public string det_tiplot { get; set; }
        public string det_codswi { get; set; }
        public string det_nombre { get; set; }
        public string det_codope { get; set; }
        public string det_nomope { get; set; }
        public string det_numref { get; set; }
        public System.DateTime det_fecini { get; set; }
        public System.DateTime det_fecven { get; set; }
        public int det_plazo_res { get; set; }
        public double det_mtoope { get; set; }
        public string det_codofi { get; set; }
        public string det_operie { get; set; }
        public int det_codlinc { get; set; }
        public string det_deslinc { get; set; }
        public string det_flagpla { get; set; }
        public int det_plaini { get; set; }
        public string det_incini { get; set; }
        public int det_plafin { get; set; }
        public string det_incfin { get; set; }
        public string det_mndswf { get; set; }
        public int det_paigar { get; set; }
        public string det_paigar_ { get; set; }
        public int det_prcpai { get; set; }
        public double det_mtopai { get; set; }
        public string det_glosa { get; set; }
        public double det_tasa { get; set; }
        public string det_flagerr { get; set; }
    }
}
