//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_ofi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sbc_ofi()
        {
            this.sbc_recf = new HashSet<sbc_recf>();
            this.sbc_reco = new HashSet<sbc_reco>();
        }
    
        public string ofi_codofi { get; set; }
        public string ofi_nomofi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbc_recf> sbc_recf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbc_reco> sbc_reco { get; set; }
    }
}
