//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_bksv
    {
        public int bksv_codcta { get; set; }
        public int bksv_codbks0 { get; set; }
        public int bksv_factor0 { get; set; }
        public int bksv_codbks1 { get; set; }
        public int bksv_factor1 { get; set; }
        public int bksv_codbks2 { get; set; }
        public int bksv_factor2 { get; set; }
        public int bksv_codbks3 { get; set; }
        public int bksv_factor3 { get; set; }
        public int bksv_codbks4 { get; set; }
        public int bksv_factor4 { get; set; }
        public int bksv_codbks5 { get; set; }
        public int bksv_factor5 { get; set; }
        public int bksv_codbks6 { get; set; }
        public int bksv_factor6 { get; set; }
        public int bksv_codbks7 { get; set; }
        public int bksv_factor7 { get; set; }
        public int bksv_codbks8 { get; set; }
        public int bksv_factor8 { get; set; }
        public int bksv_codbks9 { get; set; }
        public int bksv_factor9 { get; set; }
    }
}
