//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbc_act
    {
        public string act_numref { get; set; }
        public string act_codswi { get; set; }
        public string act_rutcli { get; set; }
        public string act_dvrut { get; set; }
        public string act_nombre { get; set; }
        public string act_codope { get; set; }
        public string act_tipope { get; set; }
        public string act_estado { get; set; }
        public string act_ofiori { get; set; }
        public string act_codmnd { get; set; }
        public string act_mtoope { get; set; }
        public string act_fecini { get; set; }
        public string act_fecven { get; set; }
        public string act_tiptas { get; set; }
        public string act_tasa { get; set; }
        public string act_spread { get; set; }
        public string act_tastot { get; set; }
        public string act_plazo { get; set; }
        public string act_operie { get; set; }
        public string act_clainv { get; set; }
    }
}
