//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbcberp
    {
        public string berp_codswi { get; set; }
        public int berp_agno { get; set; }
        public int berp_mes { get; set; }
        public int berp_codpai { get; set; }
        public int berp_codcta { get; set; }
        public System.DateTime berp_feccta { get; set; }
        public double merp_mtoori { get; set; }
        public double merp_mtodol { get; set; }
    }
}
