//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sbcvi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sbcvi()
        {
            this.sbcvisps = new HashSet<sbcvisp>();
            this.sbcvists = new HashSet<sbcvist>();
        }
    
        public string vis_codswi { get; set; }
        public System.DateTime vis_fecvis { get; set; }
        public string vis_ciudad { get; set; }
        public string vis_pais { get; set; }
        public int vis_codpai { get; set; }
        public string vis_referen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbcvisp> sbcvisps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sbcvist> sbcvists { get; set; }
    }
}
