//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.sbcor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sgt_suc
    {
        public decimal suc_succod { get; set; }
        public string suc_sucnom { get; set; }
        public decimal suc_succui { get; set; }
        public string suc_succor { get; set; }
        public string suc_sucdir { get; set; }
        public string suc_sucfon { get; set; }
        public string suc_sucfax { get; set; }
        public Nullable<decimal> suc_flgfic { get; set; }
    }
}
