//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ent/bch/infra/mci/errorDetails/v/6")]
    public partial class details : object, System.ComponentModel.INotifyPropertyChanged {
        
        private fault faultField;
        
        private System.DateTime fechaHoraInicioTrxField;
        
        private System.DateTime fechaHoraFinTrxField;
        
        private string idTransaccionNegocioField;
        
        private string errorCodeField;
        
        private error[] errorListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public fault fault {
            get {
                return this.faultField;
            }
            set {
                this.faultField = value;
                this.RaisePropertyChanged("fault");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime fechaHoraInicioTrx {
            get {
                return this.fechaHoraInicioTrxField;
            }
            set {
                this.fechaHoraInicioTrxField = value;
                this.RaisePropertyChanged("fechaHoraInicioTrx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechaHoraFinTrx {
            get {
                return this.fechaHoraFinTrxField;
            }
            set {
                this.fechaHoraFinTrxField = value;
                this.RaisePropertyChanged("fechaHoraFinTrx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public error[] errorList {
            get {
                return this.errorListField;
            }
            set {
                this.errorListField = value;
                this.RaisePropertyChanged("errorList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ent/bch/infra/mci/errorDetails/v/6")]
    public partial class fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string reasonField;
        
        private location locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public location location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ent/bch/infra/mci/errorDetails/v/6")]
    public partial class location : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nodeField;
        
        private string pipelineField;
        
        private string stageField;
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
                this.RaisePropertyChanged("node");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pipeline {
            get {
                return this.pipelineField;
            }
            set {
                this.pipelineField = value;
                this.RaisePropertyChanged("pipeline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string stage {
            get {
                return this.stageField;
            }
            set {
                this.stageField = value;
                this.RaisePropertyChanged("stage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("path");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ent/bch/infra/mci/errorDetails/v/6")]
    public partial class error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string levelField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string backEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string backEnd {
            get {
                return this.backEndField;
            }
            set {
                this.backEndField = value;
                this.RaisePropertyChanged("backEnd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFullRs/mpi")]
    public partial class respuestaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutClienteField;
        
        private string nombreField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string oficinaEjecutivoField;
        
        private string codigoEjecutivoField;
        
        private string nombreEjecutivoField;
        
        private string apellidoPaternoEjecutivoField;
        
        private string apellidoMaternoEjecutivoField;
        
        private string emailEjecutivoField;
        
        private string codigoPaisEjecutivoField;
        
        private string codigoCiudadEjecutivoField;
        
        private string telefonoField;
        
        private string segmentoField;
        
        private string marcaField;
        
        private string bancaField;
        
        private string clasificacionRiesgoField;
        
        private string actividadEconomicaField;
        
        private string categoriaField;
        
        private string codigoSegmentoField;
        
        private string codigoMarcaField;
        
        private string codigoBancaField;
        
        private string codigoActividadEconomicaField;
        
        private string fechaNacimientoField;
        
        private string nombreOficinaField;
        
        private string tipoClienteField;
        
        private string sexoField;
        
        private string direccionField;
        
        private string numeroDireccionField;
        
        private string complementoDireccionField;
        
        private string comunaField;
        
        private string ciudadField;
        
        private string regionField;
        
        private string paisField;
        
        private string tipoDespachoField;
        
        private string cuiField;
        
        private string codigoCategoriaField;
        
        private string rowIdDireccionField;
        
        private string codigoPaisFonoPartClienteField;
        
        private string codigoCiudadPartClienteField;
        
        private string fonoParticularClienteField;
        
        private string codigoPaisCelularClienteField;
        
        private string codigoCiudadCelularClienteField;
        
        private string celularParticularClienteField;
        
        private string emailParticularClienteField;
        
        private string codigoPaisFonoComClienteField;
        
        private string codigoCiudadFonoComClienteField;
        
        private string fonoComercialClienteField;
        
        private string emailComercialClienteField;
        
        private string emailAlternativoEjecutivoField;
        
        private string rutEjecutivoField;
        
        private string inhabilidadField;
        
        private string nacionalidadField;
        
        private string paisOrigenField;
        
        private string estadoCivilField;
        
        private string regimenMatrimonialField;
        
        private string tipoFATCAField;
        
        private string tinNumSeguroSocialField;
        
        private string rutContactoField;
        
        private string nombreContactoField;
        
        private string apellidoPaternoContactoField;
        
        private string apellidoMaternoContactoField;
        
        private string tipoRelacionContactoField;
        
        private string rutConyugeField;
        
        private string tipoViviendaField;
        
        private string nroDependenciaField;
        
        private string anoResidenciaField;
        
        private string marcaFuncionarioField;
        
        private string nivelEstudiosField;
        
        private string profesionField;
        
        private string rutEmpleadorField;
        
        private string nombreEmpleadorField;
        
        private string cargoField;
        
        private string tipoContratoField;
        
        private string fechaContratoField;
        
        private string tipoRentaField;
        
        private string tipoPagoPensionField;
        
        private string fondoPensionField;
        
        private string usoBancoMontoField;
        
        private string tipoIngrLiquidoField;
        
        private string montoIngresoField;
        
        private string fechaActualizacionIngresoField;
        
        private string marcaComparteBcaPrivadaField;
        
        private string idiomaField;
        
        private string flagEnviaCorreoField;
        
        private string desSexoField;
        
        private string desCuiField;
        
        private string comportamientoField;
        
        private string fechaDefuncionField;
        
        private string composicionInstitucionalField;
        
        private string evaluacionRiesgoField;
        
        private string tipoClienteNormativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rutCliente {
            get {
                return this.rutClienteField;
            }
            set {
                this.rutClienteField = value;
                this.RaisePropertyChanged("rutCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string oficinaEjecutivo {
            get {
                return this.oficinaEjecutivoField;
            }
            set {
                this.oficinaEjecutivoField = value;
                this.RaisePropertyChanged("oficinaEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string codigoEjecutivo {
            get {
                return this.codigoEjecutivoField;
            }
            set {
                this.codigoEjecutivoField = value;
                this.RaisePropertyChanged("codigoEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string nombreEjecutivo {
            get {
                return this.nombreEjecutivoField;
            }
            set {
                this.nombreEjecutivoField = value;
                this.RaisePropertyChanged("nombreEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string apellidoPaternoEjecutivo {
            get {
                return this.apellidoPaternoEjecutivoField;
            }
            set {
                this.apellidoPaternoEjecutivoField = value;
                this.RaisePropertyChanged("apellidoPaternoEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string apellidoMaternoEjecutivo {
            get {
                return this.apellidoMaternoEjecutivoField;
            }
            set {
                this.apellidoMaternoEjecutivoField = value;
                this.RaisePropertyChanged("apellidoMaternoEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string emailEjecutivo {
            get {
                return this.emailEjecutivoField;
            }
            set {
                this.emailEjecutivoField = value;
                this.RaisePropertyChanged("emailEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string codigoPaisEjecutivo {
            get {
                return this.codigoPaisEjecutivoField;
            }
            set {
                this.codigoPaisEjecutivoField = value;
                this.RaisePropertyChanged("codigoPaisEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string codigoCiudadEjecutivo {
            get {
                return this.codigoCiudadEjecutivoField;
            }
            set {
                this.codigoCiudadEjecutivoField = value;
                this.RaisePropertyChanged("codigoCiudadEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
                this.RaisePropertyChanged("segmento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string banca {
            get {
                return this.bancaField;
            }
            set {
                this.bancaField = value;
                this.RaisePropertyChanged("banca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string clasificacionRiesgo {
            get {
                return this.clasificacionRiesgoField;
            }
            set {
                this.clasificacionRiesgoField = value;
                this.RaisePropertyChanged("clasificacionRiesgo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string actividadEconomica {
            get {
                return this.actividadEconomicaField;
            }
            set {
                this.actividadEconomicaField = value;
                this.RaisePropertyChanged("actividadEconomica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string codigoSegmento {
            get {
                return this.codigoSegmentoField;
            }
            set {
                this.codigoSegmentoField = value;
                this.RaisePropertyChanged("codigoSegmento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string codigoMarca {
            get {
                return this.codigoMarcaField;
            }
            set {
                this.codigoMarcaField = value;
                this.RaisePropertyChanged("codigoMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string codigoBanca {
            get {
                return this.codigoBancaField;
            }
            set {
                this.codigoBancaField = value;
                this.RaisePropertyChanged("codigoBanca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string codigoActividadEconomica {
            get {
                return this.codigoActividadEconomicaField;
            }
            set {
                this.codigoActividadEconomicaField = value;
                this.RaisePropertyChanged("codigoActividadEconomica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string nombreOficina {
            get {
                return this.nombreOficinaField;
            }
            set {
                this.nombreOficinaField = value;
                this.RaisePropertyChanged("nombreOficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string numeroDireccion {
            get {
                return this.numeroDireccionField;
            }
            set {
                this.numeroDireccionField = value;
                this.RaisePropertyChanged("numeroDireccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string complementoDireccion {
            get {
                return this.complementoDireccionField;
            }
            set {
                this.complementoDireccionField = value;
                this.RaisePropertyChanged("complementoDireccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("comuna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string tipoDespacho {
            get {
                return this.tipoDespachoField;
            }
            set {
                this.tipoDespachoField = value;
                this.RaisePropertyChanged("tipoDespacho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string cui {
            get {
                return this.cuiField;
            }
            set {
                this.cuiField = value;
                this.RaisePropertyChanged("cui");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string codigoCategoria {
            get {
                return this.codigoCategoriaField;
            }
            set {
                this.codigoCategoriaField = value;
                this.RaisePropertyChanged("codigoCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string rowIdDireccion {
            get {
                return this.rowIdDireccionField;
            }
            set {
                this.rowIdDireccionField = value;
                this.RaisePropertyChanged("rowIdDireccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string codigoPaisFonoPartCliente {
            get {
                return this.codigoPaisFonoPartClienteField;
            }
            set {
                this.codigoPaisFonoPartClienteField = value;
                this.RaisePropertyChanged("codigoPaisFonoPartCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string codigoCiudadPartCliente {
            get {
                return this.codigoCiudadPartClienteField;
            }
            set {
                this.codigoCiudadPartClienteField = value;
                this.RaisePropertyChanged("codigoCiudadPartCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string fonoParticularCliente {
            get {
                return this.fonoParticularClienteField;
            }
            set {
                this.fonoParticularClienteField = value;
                this.RaisePropertyChanged("fonoParticularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string codigoPaisCelularCliente {
            get {
                return this.codigoPaisCelularClienteField;
            }
            set {
                this.codigoPaisCelularClienteField = value;
                this.RaisePropertyChanged("codigoPaisCelularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string codigoCiudadCelularCliente {
            get {
                return this.codigoCiudadCelularClienteField;
            }
            set {
                this.codigoCiudadCelularClienteField = value;
                this.RaisePropertyChanged("codigoCiudadCelularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string celularParticularCliente {
            get {
                return this.celularParticularClienteField;
            }
            set {
                this.celularParticularClienteField = value;
                this.RaisePropertyChanged("celularParticularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string emailParticularCliente {
            get {
                return this.emailParticularClienteField;
            }
            set {
                this.emailParticularClienteField = value;
                this.RaisePropertyChanged("emailParticularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string codigoPaisFonoComCliente {
            get {
                return this.codigoPaisFonoComClienteField;
            }
            set {
                this.codigoPaisFonoComClienteField = value;
                this.RaisePropertyChanged("codigoPaisFonoComCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string codigoCiudadFonoComCliente {
            get {
                return this.codigoCiudadFonoComClienteField;
            }
            set {
                this.codigoCiudadFonoComClienteField = value;
                this.RaisePropertyChanged("codigoCiudadFonoComCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string fonoComercialCliente {
            get {
                return this.fonoComercialClienteField;
            }
            set {
                this.fonoComercialClienteField = value;
                this.RaisePropertyChanged("fonoComercialCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string emailComercialCliente {
            get {
                return this.emailComercialClienteField;
            }
            set {
                this.emailComercialClienteField = value;
                this.RaisePropertyChanged("emailComercialCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string emailAlternativoEjecutivo {
            get {
                return this.emailAlternativoEjecutivoField;
            }
            set {
                this.emailAlternativoEjecutivoField = value;
                this.RaisePropertyChanged("emailAlternativoEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string rutEjecutivo {
            get {
                return this.rutEjecutivoField;
            }
            set {
                this.rutEjecutivoField = value;
                this.RaisePropertyChanged("rutEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string inhabilidad {
            get {
                return this.inhabilidadField;
            }
            set {
                this.inhabilidadField = value;
                this.RaisePropertyChanged("inhabilidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string paisOrigen {
            get {
                return this.paisOrigenField;
            }
            set {
                this.paisOrigenField = value;
                this.RaisePropertyChanged("paisOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("estadoCivil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string regimenMatrimonial {
            get {
                return this.regimenMatrimonialField;
            }
            set {
                this.regimenMatrimonialField = value;
                this.RaisePropertyChanged("regimenMatrimonial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string tipoFATCA {
            get {
                return this.tipoFATCAField;
            }
            set {
                this.tipoFATCAField = value;
                this.RaisePropertyChanged("tipoFATCA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string tinNumSeguroSocial {
            get {
                return this.tinNumSeguroSocialField;
            }
            set {
                this.tinNumSeguroSocialField = value;
                this.RaisePropertyChanged("tinNumSeguroSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string rutContacto {
            get {
                return this.rutContactoField;
            }
            set {
                this.rutContactoField = value;
                this.RaisePropertyChanged("rutContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string nombreContacto {
            get {
                return this.nombreContactoField;
            }
            set {
                this.nombreContactoField = value;
                this.RaisePropertyChanged("nombreContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string apellidoPaternoContacto {
            get {
                return this.apellidoPaternoContactoField;
            }
            set {
                this.apellidoPaternoContactoField = value;
                this.RaisePropertyChanged("apellidoPaternoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string apellidoMaternoContacto {
            get {
                return this.apellidoMaternoContactoField;
            }
            set {
                this.apellidoMaternoContactoField = value;
                this.RaisePropertyChanged("apellidoMaternoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string tipoRelacionContacto {
            get {
                return this.tipoRelacionContactoField;
            }
            set {
                this.tipoRelacionContactoField = value;
                this.RaisePropertyChanged("tipoRelacionContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string rutConyuge {
            get {
                return this.rutConyugeField;
            }
            set {
                this.rutConyugeField = value;
                this.RaisePropertyChanged("rutConyuge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string tipoVivienda {
            get {
                return this.tipoViviendaField;
            }
            set {
                this.tipoViviendaField = value;
                this.RaisePropertyChanged("tipoVivienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string nroDependencia {
            get {
                return this.nroDependenciaField;
            }
            set {
                this.nroDependenciaField = value;
                this.RaisePropertyChanged("nroDependencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string anoResidencia {
            get {
                return this.anoResidenciaField;
            }
            set {
                this.anoResidenciaField = value;
                this.RaisePropertyChanged("anoResidencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string marcaFuncionario {
            get {
                return this.marcaFuncionarioField;
            }
            set {
                this.marcaFuncionarioField = value;
                this.RaisePropertyChanged("marcaFuncionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string nivelEstudios {
            get {
                return this.nivelEstudiosField;
            }
            set {
                this.nivelEstudiosField = value;
                this.RaisePropertyChanged("nivelEstudios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string profesion {
            get {
                return this.profesionField;
            }
            set {
                this.profesionField = value;
                this.RaisePropertyChanged("profesion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public string rutEmpleador {
            get {
                return this.rutEmpleadorField;
            }
            set {
                this.rutEmpleadorField = value;
                this.RaisePropertyChanged("rutEmpleador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string nombreEmpleador {
            get {
                return this.nombreEmpleadorField;
            }
            set {
                this.nombreEmpleadorField = value;
                this.RaisePropertyChanged("nombreEmpleador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public string tipoContrato {
            get {
                return this.tipoContratoField;
            }
            set {
                this.tipoContratoField = value;
                this.RaisePropertyChanged("tipoContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string fechaContrato {
            get {
                return this.fechaContratoField;
            }
            set {
                this.fechaContratoField = value;
                this.RaisePropertyChanged("fechaContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public string tipoRenta {
            get {
                return this.tipoRentaField;
            }
            set {
                this.tipoRentaField = value;
                this.RaisePropertyChanged("tipoRenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public string tipoPagoPension {
            get {
                return this.tipoPagoPensionField;
            }
            set {
                this.tipoPagoPensionField = value;
                this.RaisePropertyChanged("tipoPagoPension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=77)]
        public string fondoPension {
            get {
                return this.fondoPensionField;
            }
            set {
                this.fondoPensionField = value;
                this.RaisePropertyChanged("fondoPension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=78)]
        public string usoBancoMonto {
            get {
                return this.usoBancoMontoField;
            }
            set {
                this.usoBancoMontoField = value;
                this.RaisePropertyChanged("usoBancoMonto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=79)]
        public string tipoIngrLiquido {
            get {
                return this.tipoIngrLiquidoField;
            }
            set {
                this.tipoIngrLiquidoField = value;
                this.RaisePropertyChanged("tipoIngrLiquido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=80)]
        public string montoIngreso {
            get {
                return this.montoIngresoField;
            }
            set {
                this.montoIngresoField = value;
                this.RaisePropertyChanged("montoIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=81)]
        public string fechaActualizacionIngreso {
            get {
                return this.fechaActualizacionIngresoField;
            }
            set {
                this.fechaActualizacionIngresoField = value;
                this.RaisePropertyChanged("fechaActualizacionIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=82)]
        public string marcaComparteBcaPrivada {
            get {
                return this.marcaComparteBcaPrivadaField;
            }
            set {
                this.marcaComparteBcaPrivadaField = value;
                this.RaisePropertyChanged("marcaComparteBcaPrivada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=83)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=84)]
        public string flagEnviaCorreo {
            get {
                return this.flagEnviaCorreoField;
            }
            set {
                this.flagEnviaCorreoField = value;
                this.RaisePropertyChanged("flagEnviaCorreo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=85)]
        public string desSexo {
            get {
                return this.desSexoField;
            }
            set {
                this.desSexoField = value;
                this.RaisePropertyChanged("desSexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=86)]
        public string desCui {
            get {
                return this.desCuiField;
            }
            set {
                this.desCuiField = value;
                this.RaisePropertyChanged("desCui");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=87)]
        public string comportamiento {
            get {
                return this.comportamientoField;
            }
            set {
                this.comportamientoField = value;
                this.RaisePropertyChanged("comportamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=88)]
        public string fechaDefuncion {
            get {
                return this.fechaDefuncionField;
            }
            set {
                this.fechaDefuncionField = value;
                this.RaisePropertyChanged("fechaDefuncion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=89)]
        public string composicionInstitucional {
            get {
                return this.composicionInstitucionalField;
            }
            set {
                this.composicionInstitucionalField = value;
                this.RaisePropertyChanged("composicionInstitucional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=90)]
        public string evaluacionRiesgo {
            get {
                return this.evaluacionRiesgoField;
            }
            set {
                this.evaluacionRiesgoField = value;
                this.RaisePropertyChanged("evaluacionRiesgo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=91)]
        public string tipoClienteNormativo {
            get {
                return this.tipoClienteNormativoField;
            }
            set {
                this.tipoClienteNormativoField = value;
                this.RaisePropertyChanged("tipoClienteNormativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFullRs/mpi")]
    public partial class consultarFichaClienteFullRsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoRespuestaField;
        
        private string glosaRespuestaField;
        
        private respuestaType respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string glosaRespuesta {
            get {
                return this.glosaRespuestaField;
            }
            set {
                this.glosaRespuestaField = value;
                this.RaisePropertyChanged("glosaRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public respuestaType respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFullRq/mpi")]
    public partial class consultarFichaClienteFullRqType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutClienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rutCliente {
            get {
                return this.rutClienteField;
            }
            set {
                this.rutClienteField = value;
                this.RaisePropertyChanged("rutCliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFull/v/3", ConfigurationName="CTR.ConsultarFichaClienteFull.consultarFichaClienteFullPort")]
    public interface consultarFichaClienteFullPort {
        
        // CODEGEN: Generating message contract since the operation consultarFichaClienteFull is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFull/v/3/consultarFicha" +
            "ClienteFullPort/consultarFichaClienteFullRequest", ReplyAction="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFull/v/3/consultarFicha" +
            "ClienteFullPort/consultarFichaClienteFullResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.details), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="details", Namespace="http://osb.bancochile.cl/ent/bch/infra/mci/errorDetails/v/6")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullResponse consultarFichaClienteFull(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFull/v/3/consultarFicha" +
            "ClienteFullPort/consultarFichaClienteFullRequest", ReplyAction="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFull/v/3/consultarFicha" +
            "ClienteFullPort/consultarFichaClienteFullResponse")]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullResponse> consultarFichaClienteFullAsync(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ent/bch/neg/mci/cabeceraServicios/v/4")]
    public partial class HeaderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DatosConsumidor datosConsumidorField;
        
        private DatosTransaccion datosTransaccionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DatosConsumidor datosConsumidor {
            get {
                return this.datosConsumidorField;
            }
            set {
                this.datosConsumidorField = value;
                this.RaisePropertyChanged("datosConsumidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DatosTransaccion datosTransaccion {
            get {
                return this.datosTransaccionField;
            }
            set {
                this.datosTransaccionField = value;
                this.RaisePropertyChanged("datosTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ent/bch/infra/mci/cabeceraServicios/v/3")]
    public partial class DatosConsumidor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string pathServicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pathServices {
            get {
                return this.pathServicesField;
            }
            set {
                this.pathServicesField = value;
                this.RaisePropertyChanged("pathServices");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ent/bch/neg/mci/cabeceraServicios/v/4")]
    public partial class DatosTransaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionNegocioField;
        
        private string internalCodeField;
        
        private System.DateTime fechaHoraField;
        
        private string idCanalField;
        
        private string numeroSucursalField;
        
        private string prioridadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string idCanal {
            get {
                return this.idCanalField;
            }
            set {
                this.idCanalField = value;
                this.RaisePropertyChanged("idCanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string numeroSucursal {
            get {
                return this.numeroSucursalField;
            }
            set {
                this.numeroSucursalField = value;
                this.RaisePropertyChanged("numeroSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string prioridad {
            get {
                return this.prioridadField;
            }
            set {
                this.prioridadField = value;
                this.RaisePropertyChanged("prioridad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ent/bch/neg/mci/cabeceraServicios/v/4")]
    public partial class HeaderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaInicioTrxField;
        
        private bool fechaInicioTrxFieldSpecified;
        
        private System.DateTime fechaFinTrxField;
        
        private bool fechaFinTrxFieldSpecified;
        
        private string internalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime fechaInicioTrx {
            get {
                return this.fechaInicioTrxField;
            }
            set {
                this.fechaInicioTrxField = value;
                this.RaisePropertyChanged("fechaInicioTrx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioTrxSpecified {
            get {
                return this.fechaInicioTrxFieldSpecified;
            }
            set {
                this.fechaInicioTrxFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioTrxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechaFinTrx {
            get {
                return this.fechaFinTrxField;
            }
            set {
                this.fechaFinTrxField = value;
                this.RaisePropertyChanged("fechaFinTrx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinTrxSpecified {
            get {
                return this.fechaFinTrxFieldSpecified;
            }
            set {
                this.fechaFinTrxFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinTrxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarFichaClienteFullRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/ent/bch/neg/mci/cabeceraServicios/v/4")]
        public BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.HeaderRequest headerRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFullRq/mpi", Order=0)]
        public BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRqType consultarFichaClienteFullRq;
        
        public consultarFichaClienteFullRequest() {
        }
        
        public consultarFichaClienteFullRequest(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.HeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRqType consultarFichaClienteFullRq) {
            this.headerRequest = headerRequest;
            this.consultarFichaClienteFullRq = consultarFichaClienteFullRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarFichaClienteFullResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/ent/bch/neg/mci/cabeceraServicios/v/4")]
        public BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.HeaderResponse headerResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/bch/neg/cif/consultarFichaClienteFullRs/mpi", Order=0)]
        public BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRsType consultarFichaClienteFullRs;
        
        public consultarFichaClienteFullResponse() {
        }
        
        public consultarFichaClienteFullResponse(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.HeaderResponse headerResponse, BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRsType consultarFichaClienteFullRs) {
            this.headerResponse = headerResponse;
            this.consultarFichaClienteFullRs = consultarFichaClienteFullRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface consultarFichaClienteFullPortChannel : BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class consultarFichaClienteFullPortClient : System.ServiceModel.ClientBase<BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullPort>, BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullPort {
        
        public consultarFichaClienteFullPortClient() {
        }
        
        public consultarFichaClienteFullPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public consultarFichaClienteFullPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public consultarFichaClienteFullPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public consultarFichaClienteFullPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullResponse BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullPort.consultarFichaClienteFull(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRequest request) {
            return base.Channel.consultarFichaClienteFull(request);
        }
        
        public BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.HeaderResponse consultarFichaClienteFull(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.HeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRqType consultarFichaClienteFullRq, out BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRsType consultarFichaClienteFullRs) {
            BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRequest inValue = new BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRequest();
            inValue.headerRequest = headerRequest;
            inValue.consultarFichaClienteFullRq = consultarFichaClienteFullRq;
            BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullResponse retVal = ((BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullPort)(this)).consultarFichaClienteFull(inValue);
            consultarFichaClienteFullRs = retVal.consultarFichaClienteFullRs;
            return retVal.headerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullResponse> BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullPort.consultarFichaClienteFullAsync(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRequest request) {
            return base.Channel.consultarFichaClienteFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullResponse> consultarFichaClienteFullAsync(BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.HeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRqType consultarFichaClienteFullRq) {
            BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRequest inValue = new BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullRequest();
            inValue.headerRequest = headerRequest;
            inValue.consultarFichaClienteFullRq = consultarFichaClienteFullRq;
            return ((BCH.Comex.Data.DAL.Services.CTR.ConsultarFichaClienteFull.consultarFichaClienteFullPort)(this)).consultarFichaClienteFullAsync(inValue);
        }
    }
}
