//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://osb.bancochile.cl/ConsultasSaldoCuenta/", ConfigurationName="XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuenta")]
    public interface ConsultasSaldoCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl/ConsultasSaldoCuenta/ConsultasSaldoCuenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaResponse ConsultasSaldoCuenta(BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl/ConsultasSaldoCuenta/ConsultasSaldoCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaResponse> ConsultasSaldoCuentaAsync(BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosHeaderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosConsumidor consumidorField;
        
        private datosTransaccion transaccionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosConsumidor consumidor {
            get {
                return this.consumidorField;
            }
            set {
                this.consumidorField = value;
                this.RaisePropertyChanged("consumidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public datosTransaccion transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosConsumidor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idAppField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idApp {
            get {
                return this.idAppField;
            }
            set {
                this.idAppField = value;
                this.RaisePropertyChanged("idApp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="datosTransaccion", Namespace="http://osb.bancochile.cl/common/HeaderResponse")]
    public partial class datosTransaccion1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.Nullable<System.DateTime> fechaHoraInicioTrxField;
        
        private System.Nullable<System.DateTime> fechaHoraFinTrxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> fechaHoraInicioTrx {
            get {
                return this.fechaHoraInicioTrxField;
            }
            set {
                this.fechaHoraInicioTrxField = value;
                this.RaisePropertyChanged("fechaHoraInicioTrx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fechaHoraFinTrx {
            get {
                return this.fechaHoraFinTrxField;
            }
            set {
                this.fechaHoraFinTrxField = value;
                this.RaisePropertyChanged("fechaHoraFinTrx");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderResponse")]
    public partial class datosHeaderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosTransaccion1 transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosTransaccion1 transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosTransaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaHoraField;
        
        private string canalField;
        
        private string sucursalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("sucursal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ConsultasSaldoCuenta/OpConsultasSaldoCuentaResponse")]
    public partial class CuentaRelacionadaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroCuentaRelacionadaField;
        
        private string montoLineaAutorizadoField;
        
        private string montoLineaDisponibleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroCuentaRelacionada {
            get {
                return this.numeroCuentaRelacionadaField;
            }
            set {
                this.numeroCuentaRelacionadaField = value;
                this.RaisePropertyChanged("NumeroCuentaRelacionada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MontoLineaAutorizado {
            get {
                return this.montoLineaAutorizadoField;
            }
            set {
                this.montoLineaAutorizadoField = value;
                this.RaisePropertyChanged("MontoLineaAutorizado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MontoLineaDisponible {
            get {
                return this.montoLineaDisponibleField;
            }
            set {
                this.montoLineaDisponibleField = value;
                this.RaisePropertyChanged("MontoLineaDisponible");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ConsultasSaldoCuenta/OpConsultasSaldoCuentaResponse")]
    public partial class CuentaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroCuentaField;
        
        private string saldoDisponibleField;
        
        private string saldoContableField;
        
        private string retencion1DiaField;
        
        private string retencionNDiaField;
        
        private string limiteCreditoField;
        
        private string sobregiroPactadoField;
        
        private string montoBloqueadoField;
        
        private string oficinaField;
        
        private string monedaField;
        
        private string nombreTitularField;
        
        private string nombreSegundoTitularField;
        
        private string montoAutorizadoLSPField;
        
        private string montoDebitoTanqueadoField;
        
        private string montoCrebitoTanqueadoField;
        
        private string montoRetencionTanqueadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
                this.RaisePropertyChanged("NumeroCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SaldoDisponible {
            get {
                return this.saldoDisponibleField;
            }
            set {
                this.saldoDisponibleField = value;
                this.RaisePropertyChanged("SaldoDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SaldoContable {
            get {
                return this.saldoContableField;
            }
            set {
                this.saldoContableField = value;
                this.RaisePropertyChanged("SaldoContable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Retencion1Dia {
            get {
                return this.retencion1DiaField;
            }
            set {
                this.retencion1DiaField = value;
                this.RaisePropertyChanged("Retencion1Dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RetencionNDia {
            get {
                return this.retencionNDiaField;
            }
            set {
                this.retencionNDiaField = value;
                this.RaisePropertyChanged("RetencionNDia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LimiteCredito {
            get {
                return this.limiteCreditoField;
            }
            set {
                this.limiteCreditoField = value;
                this.RaisePropertyChanged("LimiteCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SobregiroPactado {
            get {
                return this.sobregiroPactadoField;
            }
            set {
                this.sobregiroPactadoField = value;
                this.RaisePropertyChanged("SobregiroPactado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MontoBloqueado {
            get {
                return this.montoBloqueadoField;
            }
            set {
                this.montoBloqueadoField = value;
                this.RaisePropertyChanged("MontoBloqueado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Oficina {
            get {
                return this.oficinaField;
            }
            set {
                this.oficinaField = value;
                this.RaisePropertyChanged("Oficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string NombreTitular {
            get {
                return this.nombreTitularField;
            }
            set {
                this.nombreTitularField = value;
                this.RaisePropertyChanged("NombreTitular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NombreSegundoTitular {
            get {
                return this.nombreSegundoTitularField;
            }
            set {
                this.nombreSegundoTitularField = value;
                this.RaisePropertyChanged("NombreSegundoTitular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string MontoAutorizadoLSP {
            get {
                return this.montoAutorizadoLSPField;
            }
            set {
                this.montoAutorizadoLSPField = value;
                this.RaisePropertyChanged("MontoAutorizadoLSP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string montoDebitoTanqueado {
            get {
                return this.montoDebitoTanqueadoField;
            }
            set {
                this.montoDebitoTanqueadoField = value;
                this.RaisePropertyChanged("montoDebitoTanqueado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string montoCrebitoTanqueado {
            get {
                return this.montoCrebitoTanqueadoField;
            }
            set {
                this.montoCrebitoTanqueadoField = value;
                this.RaisePropertyChanged("montoCrebitoTanqueado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string montoRetencionTanqueado {
            get {
                return this.montoRetencionTanqueadoField;
            }
            set {
                this.montoRetencionTanqueadoField = value;
                this.RaisePropertyChanged("montoRetencionTanqueado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="cuerpo", Namespace="http://osb.bancochile.cl/ESB/ConsultasSaldoCuenta/OpConsultasSaldoCuentaResponse")]
    public partial class cuerpo1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CuentaType cuentaField;
        
        private CuentaRelacionadaType cuentaRelacionadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CuentaType Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CuentaRelacionadaType CuentaRelacionada {
            get {
                return this.cuentaRelacionadaField;
            }
            set {
                this.cuentaRelacionadaField = value;
                this.RaisePropertyChanged("CuentaRelacionada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ConsultasSaldoCuenta/OpConsultasSaldoCuentaRequest")]
    public partial class cuerpo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroCuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
                this.RaisePropertyChanged("numeroCuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultasSaldoCuenta", WrapperNamespace="http://osb.bancochile.cl/ConsultasSaldoCuenta/", IsWrapped=true)]
    public partial class ConsultasSaldoCuentaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/ConsultasSaldoCuenta/")]
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.datosHeaderRequest headerRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/ConsultasSaldoCuenta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.cuerpo cuerpo;
        
        public ConsultasSaldoCuentaRequest() {
        }
        
        public ConsultasSaldoCuentaRequest(BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.cuerpo cuerpo) {
            this.headerRequest = headerRequest;
            this.cuerpo = cuerpo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultasSaldoCuentaResponse", WrapperNamespace="http://osb.bancochile.cl/ConsultasSaldoCuenta/", IsWrapped=true)]
    public partial class ConsultasSaldoCuentaResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/ConsultasSaldoCuenta/")]
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.datosHeaderResponse headerResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/ConsultasSaldoCuenta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.cuerpo1 cuerpo;
        
        public ConsultasSaldoCuentaResponse() {
        }
        
        public ConsultasSaldoCuentaResponse(BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.datosHeaderResponse headerResponse, BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.cuerpo1 cuerpo) {
            this.headerResponse = headerResponse;
            this.cuerpo = cuerpo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultasSaldoCuentaChannel : BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultasSaldoCuentaClient : System.ServiceModel.ClientBase<BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuenta>, BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuenta {
        
        public ConsultasSaldoCuentaClient() {
        }
        
        public ConsultasSaldoCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultasSaldoCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultasSaldoCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultasSaldoCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaResponse BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuenta.ConsultasSaldoCuenta(BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaRequest request) {
            return base.Channel.ConsultasSaldoCuenta(request);
        }
        
        public BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.datosHeaderResponse ConsultasSaldoCuenta(BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.cuerpo cuerpo, out BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.cuerpo1 cuerpo1) {
            BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaRequest inValue = new BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaRequest();
            inValue.headerRequest = headerRequest;
            inValue.cuerpo = cuerpo;
            BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaResponse retVal = ((BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuenta)(this)).ConsultasSaldoCuenta(inValue);
            cuerpo1 = retVal.cuerpo;
            return retVal.headerResponse;
        }
        
        public System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaResponse> ConsultasSaldoCuentaAsync(BCH.Comex.Data.DAL.Services.XCFT.ConsultaSaldoCuenta.ConsultasSaldoCuentaRequest request) {
            return base.Channel.ConsultasSaldoCuentaAsync(request);
        }
    }
}
