//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Context.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using BCH.Comex.Core.Entities.Swift;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class swiftEntities : DbContext
    {
        public swiftEntities()
            : base("name=swiftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<joal> joals { get; set; }
        public virtual DbSet<sw_bancos> sw_bancos { get; set; }
        public virtual DbSet<sw_bancos_autorizados> sw_bancos_autorizados { get; set; }
        public virtual DbSet<sw_campos_msg> sw_campos_msg { get; set; }
        public virtual DbSet<sw_caracter_error> sw_caracter_error { get; set; }
        public virtual DbSet<sw_casillas> sw_casillas { get; set; }
        public virtual DbSet<sw_ciclos> sw_ciclos { get; set; }
        public virtual DbSet<sw_configura> sw_configura { get; set; }
        public virtual DbSet<sw_estados_msg> sw_estados_msg { get; set; }
        public virtual DbSet<sw_firmas_msg> sw_firmas_msg { get; set; }
        public virtual DbSet<sw_folios> sw_folios { get; set; }
        public virtual DbSet<sw_formato_cmx> sw_formato_cmx { get; set; }
        public virtual DbSet<sw_formatos> sw_formatos { get; set; }
        public virtual DbSet<sw_glosa_cmx> sw_glosa_cmx { get; set; }
        public virtual DbSet<sw_log_msg> sw_log_msg { get; set; }
        public virtual DbSet<sw_mensajes> sw_mensajes { get; set; }
        public virtual DbSet<sw_mensajes_add> sw_mensajes_add { get; set; }
        public virtual DbSet<sw_monedas> sw_monedas { get; set; }
        public virtual DbSet<sw_msgsend> sw_msgsend { get; set; }
        public virtual DbSet<sw_msgsend_add> sw_msgsend_add { get; set; }
        public virtual DbSet<sw_msgsend_cambio_estados> sw_msgsend_cambio_estados { get; set; }
        public virtual DbSet<sw_msgsend_cmx> sw_msgsend_cmx { get; set; }
        public virtual DbSet<sw_msgsend_cmx_dia> sw_msgsend_cmx_dia { get; set; }
        public virtual DbSet<sw_msgsend_detfile> sw_msgsend_detfile { get; set; }
        public virtual DbSet<sw_msgsend_files> sw_msgsend_files { get; set; }
        public virtual DbSet<sw_msgsend_firma> sw_msgsend_firma { get; set; }
        public virtual DbSet<sw_msgsend_ftp> sw_msgsend_ftp { get; set; }
        public virtual DbSet<sw_msgsend_log> sw_msgsend_log { get; set; }
        public virtual DbSet<sw_msgsend_nop> sw_msgsend_nop { get; set; }
        public virtual DbSet<sw_orden_firmas> sw_orden_firmas { get; set; }
        public virtual DbSet<sw_paridad> sw_paridad { get; set; }
        public virtual DbSet<sw_regla_firmas> sw_regla_firmas { get; set; }
        public virtual DbSet<sw_sce_bic> sw_sce_bic { get; set; }
        public virtual DbSet<sw_tipos_campos> sw_tipos_campos { get; set; }
        public virtual DbSet<sw_tipos_firmas> sw_tipos_firmas { get; set; }
        public virtual DbSet<sw_tipos_msg> sw_tipos_msg { get; set; }
        public virtual DbSet<sw_users_srm> sw_users_srm { get; set; }
        public virtual DbSet<sw_users_swift> sw_users_swift { get; set; }
        public virtual DbSet<sw_valor_campos> sw_valor_campos { get; set; }
        public virtual DbSet<tbl_sw_nets> tbl_sw_nets { get; set; }
        public virtual DbSet<tbl_sw_nets_det> tbl_sw_nets_det { get; set; }
        public virtual DbSet<tbl_sw_nets_sor> tbl_sw_nets_sor { get; set; }
    
        public virtual ObjectResult<string> DesencriptaMensaje2(Nullable<int> sesion, Nullable<int> secuencia)
        {
            var sesionParameter = sesion.HasValue ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(int));
    
            var secuenciaParameter = secuencia.HasValue ?
                new ObjectParameter("secuencia", secuencia) :
                new ObjectParameter("secuencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DesencriptaMensaje2", sesionParameter, secuenciaParameter);
        }
    
        public virtual int EncriptaMensajeS(Nullable<int> id_mensaje, Nullable<int> sesion, Nullable<int> secuencia, Nullable<int> casilla, Nullable<int> unidad, string tipo_msg, string prioridad, string estado_msg, string tipo_ingreso, Nullable<int> rut_digita, string banco_re, string branch_re, string banco_em, string branch_em, string moneda, Nullable<double> monto, string referencia, string beneficiario, string txt_mensaje, string comentario)
        {
            var id_mensajeParameter = id_mensaje.HasValue ?
                new ObjectParameter("id_mensaje", id_mensaje) :
                new ObjectParameter("id_mensaje", typeof(int));
    
            var sesionParameter = sesion.HasValue ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(int));
    
            var secuenciaParameter = secuencia.HasValue ?
                new ObjectParameter("secuencia", secuencia) :
                new ObjectParameter("secuencia", typeof(int));
    
            var casillaParameter = casilla.HasValue ?
                new ObjectParameter("casilla", casilla) :
                new ObjectParameter("casilla", typeof(int));
    
            var unidadParameter = unidad.HasValue ?
                new ObjectParameter("unidad", unidad) :
                new ObjectParameter("unidad", typeof(int));
    
            var tipo_msgParameter = tipo_msg != null ?
                new ObjectParameter("tipo_msg", tipo_msg) :
                new ObjectParameter("tipo_msg", typeof(string));
    
            var prioridadParameter = prioridad != null ?
                new ObjectParameter("prioridad", prioridad) :
                new ObjectParameter("prioridad", typeof(string));
    
            var estado_msgParameter = estado_msg != null ?
                new ObjectParameter("estado_msg", estado_msg) :
                new ObjectParameter("estado_msg", typeof(string));
    
            var tipo_ingresoParameter = tipo_ingreso != null ?
                new ObjectParameter("tipo_ingreso", tipo_ingreso) :
                new ObjectParameter("tipo_ingreso", typeof(string));
    
            var rut_digitaParameter = rut_digita.HasValue ?
                new ObjectParameter("rut_digita", rut_digita) :
                new ObjectParameter("rut_digita", typeof(int));
    
            var banco_reParameter = banco_re != null ?
                new ObjectParameter("banco_re", banco_re) :
                new ObjectParameter("banco_re", typeof(string));
    
            var branch_reParameter = branch_re != null ?
                new ObjectParameter("branch_re", branch_re) :
                new ObjectParameter("branch_re", typeof(string));
    
            var banco_emParameter = banco_em != null ?
                new ObjectParameter("banco_em", banco_em) :
                new ObjectParameter("banco_em", typeof(string));
    
            var branch_emParameter = branch_em != null ?
                new ObjectParameter("branch_em", branch_em) :
                new ObjectParameter("branch_em", typeof(string));
    
            var monedaParameter = moneda != null ?
                new ObjectParameter("moneda", moneda) :
                new ObjectParameter("moneda", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(double));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("referencia", referencia) :
                new ObjectParameter("referencia", typeof(string));
    
            var beneficiarioParameter = beneficiario != null ?
                new ObjectParameter("beneficiario", beneficiario) :
                new ObjectParameter("beneficiario", typeof(string));
    
            var txt_mensajeParameter = txt_mensaje != null ?
                new ObjectParameter("txt_mensaje", txt_mensaje) :
                new ObjectParameter("txt_mensaje", typeof(string));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EncriptaMensajeS", id_mensajeParameter, sesionParameter, secuenciaParameter, casillaParameter, unidadParameter, tipo_msgParameter, prioridadParameter, estado_msgParameter, tipo_ingresoParameter, rut_digitaParameter, banco_reParameter, branch_reParameter, banco_emParameter, branch_emParameter, monedaParameter, montoParameter, referenciaParameter, beneficiarioParameter, txt_mensajeParameter, comentarioParameter);
        }
    
        public virtual int proc_sw_env_trae_env_rango(Nullable<int> p_casilla, Nullable<System.DateTime> p_fecha1, Nullable<System.DateTime> p_fecha2)
        {
            var p_casillaParameter = p_casilla.HasValue ?
                new ObjectParameter("p_casilla", p_casilla) :
                new ObjectParameter("p_casilla", typeof(int));
    
            var p_fecha1Parameter = p_fecha1.HasValue ?
                new ObjectParameter("p_fecha1", p_fecha1) :
                new ObjectParameter("p_fecha1", typeof(System.DateTime));
    
            var p_fecha2Parameter = p_fecha2.HasValue ?
                new ObjectParameter("p_fecha2", p_fecha2) :
                new ObjectParameter("p_fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_sw_env_trae_env_rango", p_casillaParameter, p_fecha1Parameter, p_fecha2Parameter);
        }
    
        public virtual ObjectResult<proc_sw_rec_trae_iny_rango_Result> proc_sw_rec_trae_iny_rango(Nullable<int> p_casilla, Nullable<System.DateTime> p_fecha1, Nullable<System.DateTime> p_fecha2)
        {
            var p_casillaParameter = p_casilla.HasValue ?
                new ObjectParameter("p_casilla", p_casilla) :
                new ObjectParameter("p_casilla", typeof(int));
    
            var p_fecha1Parameter = p_fecha1.HasValue ?
                new ObjectParameter("p_fecha1", p_fecha1) :
                new ObjectParameter("p_fecha1", typeof(System.DateTime));
    
            var p_fecha2Parameter = p_fecha2.HasValue ?
                new ObjectParameter("p_fecha2", p_fecha2) :
                new ObjectParameter("p_fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_sw_rec_trae_iny_rango_Result>("proc_sw_rec_trae_iny_rango", p_casillaParameter, p_fecha1Parameter, p_fecha2Parameter);
        }
    }
}
