//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://osb.bancochile.cl/ReversaCosmos/", ConfigurationName="XCFT.ReversaCosmos.ReversaCosmos")]
    public interface ReversaCosmos {
        
        // CODEGEN: Generating message contract since message ReversaCosmosRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl//ReversaCosmos/ReversaCosmos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosResponse ReversaCosmos(BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl//ReversaCosmos/ReversaCosmos", ReplyAction="*")]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosResponse> ReversaCosmosAsync(BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosHeaderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosConsumidor consumidorField;
        
        private datosTransaccion transaccionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosConsumidor consumidor {
            get {
                return this.consumidorField;
            }
            set {
                this.consumidorField = value;
                this.RaisePropertyChanged("consumidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public datosTransaccion transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosConsumidor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idAppField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idApp {
            get {
                return this.idAppField;
            }
            set {
                this.idAppField = value;
                this.RaisePropertyChanged("idApp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="datosTransaccion", Namespace="http://osb.bancochile.cl/common/HeaderResponse")]
    public partial class datosTransaccion1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.Nullable<System.DateTime> fechaHoraInicioTrxField;
        
        private System.Nullable<System.DateTime> fechaHoraFinTrxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> fechaHoraInicioTrx {
            get {
                return this.fechaHoraInicioTrxField;
            }
            set {
                this.fechaHoraInicioTrxField = value;
                this.RaisePropertyChanged("fechaHoraInicioTrx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fechaHoraFinTrx {
            get {
                return this.fechaHoraFinTrxField;
            }
            set {
                this.fechaHoraFinTrxField = value;
                this.RaisePropertyChanged("fechaHoraFinTrx");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderResponse")]
    public partial class datosHeaderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosTransaccion1 transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosTransaccion1 transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosTransaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaHoraField;
        
        private string canalField;
        
        private string sucursalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("sucursal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosResponse")]
    public partial class respReversaCosmos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Respuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Respuesta Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosResponse")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionRetornoField;
        
        private Mensajes[] mensajesField;
        
        private Campos[] camposField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descripcionRetorno {
            get {
                return this.descripcionRetornoField;
            }
            set {
                this.descripcionRetornoField = value;
                this.RaisePropertyChanged("descripcionRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mensajes", Order=1)]
        public Mensajes[] Mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
                this.RaisePropertyChanged("Mensajes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Campos", Order=2)]
        public Campos[] Campos {
            get {
                return this.camposField;
            }
            set {
                this.camposField = value;
                this.RaisePropertyChanged("Campos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosResponse")]
    public partial class Mensajes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoMovimientoField;
        
        private string codigoMensajeField;
        
        private string descripcionMensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string tipoMovimiento {
            get {
                return this.tipoMovimientoField;
            }
            set {
                this.tipoMovimientoField = value;
                this.RaisePropertyChanged("tipoMovimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string descripcionMensaje {
            get {
                return this.descripcionMensajeField;
            }
            set {
                this.descripcionMensajeField = value;
                this.RaisePropertyChanged("descripcionMensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosResponse")]
    public partial class Campos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreCampoField;
        
        private string valorCampoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string nombreCampo {
            get {
                return this.nombreCampoField;
            }
            set {
                this.nombreCampoField = value;
                this.RaisePropertyChanged("nombreCampo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string valorCampo {
            get {
                return this.valorCampoField;
            }
            set {
                this.valorCampoField = value;
                this.RaisePropertyChanged("valorCampo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosRequest")]
    public partial class reqReversaCosmos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DatosCabeceraNegocio datosCabeceraNegocioField;
        
        private DatosNegocio datosNegocioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DatosCabeceraNegocio DatosCabeceraNegocio {
            get {
                return this.datosCabeceraNegocioField;
            }
            set {
                this.datosCabeceraNegocioField = value;
                this.RaisePropertyChanged("DatosCabeceraNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DatosNegocio DatosNegocio {
            get {
                return this.datosNegocioField;
            }
            set {
                this.datosNegocioField = value;
                this.RaisePropertyChanged("DatosNegocio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosRequest")]
    public partial class DatosCabeceraNegocio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutOperadoraField;
        
        private string cajeroField;
        
        private string bancoDestinoField;
        
        private string bancoOrigenField;
        
        private string rutClienteField;
        
        private string oficinaOrigenTxField;
        
        private string cUIOrigenTxField;
        
        private string oficinaOrigenExternaTxField;
        
        private string canalOrigenTxField;
        
        private string rutSupervisorField;
        
        private string supervisorField;
        
        private System.DateTime fechaContableField;
        
        private System.DateTime fechaHoraCorrienteTxField;
        
        private string horarioField;
        
        private string txidField;
        
        private string txidParaReversarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rutOperadora {
            get {
                return this.rutOperadoraField;
            }
            set {
                this.rutOperadoraField = value;
                this.RaisePropertyChanged("rutOperadora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Cajero {
            get {
                return this.cajeroField;
            }
            set {
                this.cajeroField = value;
                this.RaisePropertyChanged("Cajero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string bancoDestino {
            get {
                return this.bancoDestinoField;
            }
            set {
                this.bancoDestinoField = value;
                this.RaisePropertyChanged("bancoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string bancoOrigen {
            get {
                return this.bancoOrigenField;
            }
            set {
                this.bancoOrigenField = value;
                this.RaisePropertyChanged("bancoOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string rutCliente {
            get {
                return this.rutClienteField;
            }
            set {
                this.rutClienteField = value;
                this.RaisePropertyChanged("rutCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string oficinaOrigenTx {
            get {
                return this.oficinaOrigenTxField;
            }
            set {
                this.oficinaOrigenTxField = value;
                this.RaisePropertyChanged("oficinaOrigenTx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string CUIOrigenTx {
            get {
                return this.cUIOrigenTxField;
            }
            set {
                this.cUIOrigenTxField = value;
                this.RaisePropertyChanged("CUIOrigenTx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string oficinaOrigenExternaTx {
            get {
                return this.oficinaOrigenExternaTxField;
            }
            set {
                this.oficinaOrigenExternaTxField = value;
                this.RaisePropertyChanged("oficinaOrigenExternaTx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string canalOrigenTx {
            get {
                return this.canalOrigenTxField;
            }
            set {
                this.canalOrigenTxField = value;
                this.RaisePropertyChanged("canalOrigenTx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string rutSupervisor {
            get {
                return this.rutSupervisorField;
            }
            set {
                this.rutSupervisorField = value;
                this.RaisePropertyChanged("rutSupervisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string supervisor {
            get {
                return this.supervisorField;
            }
            set {
                this.supervisorField = value;
                this.RaisePropertyChanged("supervisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=11)]
        public System.DateTime fechaContable {
            get {
                return this.fechaContableField;
            }
            set {
                this.fechaContableField = value;
                this.RaisePropertyChanged("fechaContable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime fechaHoraCorrienteTx {
            get {
                return this.fechaHoraCorrienteTxField;
            }
            set {
                this.fechaHoraCorrienteTxField = value;
                this.RaisePropertyChanged("fechaHoraCorrienteTx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Horario {
            get {
                return this.horarioField;
            }
            set {
                this.horarioField = value;
                this.RaisePropertyChanged("Horario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string txid {
            get {
                return this.txidField;
            }
            set {
                this.txidField = value;
                this.RaisePropertyChanged("txid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string txidParaReversar {
            get {
                return this.txidParaReversarField;
            }
            set {
                this.txidParaReversarField = value;
                this.RaisePropertyChanged("txidParaReversar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosRequest")]
    public partial class DatosNegocio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cuentaField;
        
        private string serialdelchequeField;
        
        private string codigoCartolaCosmosField;
        
        private string montoField;
        
        private string monedaField;
        
        private string cuentadeCargoField;
        
        private ListadataCartola listadataCartolaField;
        
        private dataMT942 dataMT942Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Serialdelcheque {
            get {
                return this.serialdelchequeField;
            }
            set {
                this.serialdelchequeField = value;
                this.RaisePropertyChanged("Serialdelcheque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoCartolaCosmos {
            get {
                return this.codigoCartolaCosmosField;
            }
            set {
                this.codigoCartolaCosmosField = value;
                this.RaisePropertyChanged("codigoCartolaCosmos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("Monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string CuentadeCargo {
            get {
                return this.cuentadeCargoField;
            }
            set {
                this.cuentadeCargoField = value;
                this.RaisePropertyChanged("CuentadeCargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ListadataCartola ListadataCartola {
            get {
                return this.listadataCartolaField;
            }
            set {
                this.listadataCartolaField = value;
                this.RaisePropertyChanged("ListadataCartola");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public dataMT942 dataMT942 {
            get {
                return this.dataMT942Field;
            }
            set {
                this.dataMT942Field = value;
                this.RaisePropertyChanged("dataMT942");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosRequest")]
    public partial class ListadataCartola : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dataCartola dataCartolaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public dataCartola dataCartola {
            get {
                return this.dataCartolaField;
            }
            set {
                this.dataCartolaField = value;
                this.RaisePropertyChanged("dataCartola");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosRequest")]
    public partial class dataCartola : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreCampoField;
        
        private string valorCampoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string NombreCampo {
            get {
                return this.nombreCampoField;
            }
            set {
                this.nombreCampoField = value;
                this.RaisePropertyChanged("NombreCampo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ValorCampo {
            get {
                return this.valorCampoField;
            }
            set {
                this.valorCampoField = value;
                this.RaisePropertyChanged("ValorCampo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosRequest")]
    public partial class dataMT942 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mt942Campo61 mt942Campo61Field;
        
        private string mt942CodigoTxCosmosField;
        
        private string mt942TipoProductoCosmosField;
        
        private string mt942InfoAdicional2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public mt942Campo61 mt942Campo61 {
            get {
                return this.mt942Campo61Field;
            }
            set {
                this.mt942Campo61Field = value;
                this.RaisePropertyChanged("mt942Campo61");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mt942CodigoTxCosmos {
            get {
                return this.mt942CodigoTxCosmosField;
            }
            set {
                this.mt942CodigoTxCosmosField = value;
                this.RaisePropertyChanged("mt942CodigoTxCosmos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mt942TipoProductoCosmos {
            get {
                return this.mt942TipoProductoCosmosField;
            }
            set {
                this.mt942TipoProductoCosmosField = value;
                this.RaisePropertyChanged("mt942TipoProductoCosmos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mt942InfoAdicional-2", IsNullable=true, Order=3)]
        public string mt942InfoAdicional2 {
            get {
                return this.mt942InfoAdicional2Field;
            }
            set {
                this.mt942InfoAdicional2Field = value;
                this.RaisePropertyChanged("mt942InfoAdicional2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/ReversaCosmos/OpReversaCosmosRequest")]
    public partial class mt942Campo61 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaValutaField;
        
        private string markDebitCreditField;
        
        private string txTypeField;
        
        private string referenciaClienteField;
        
        private string referenciaBCHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaValuta {
            get {
                return this.fechaValutaField;
            }
            set {
                this.fechaValutaField = value;
                this.RaisePropertyChanged("FechaValuta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MarkDebitCredit {
            get {
                return this.markDebitCreditField;
            }
            set {
                this.markDebitCreditField = value;
                this.RaisePropertyChanged("MarkDebitCredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TxType {
            get {
                return this.txTypeField;
            }
            set {
                this.txTypeField = value;
                this.RaisePropertyChanged("TxType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReferenciaCliente {
            get {
                return this.referenciaClienteField;
            }
            set {
                this.referenciaClienteField = value;
                this.RaisePropertyChanged("ReferenciaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReferenciaBCH {
            get {
                return this.referenciaBCHField;
            }
            set {
                this.referenciaBCHField = value;
                this.RaisePropertyChanged("ReferenciaBCH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReversaCosmos", WrapperNamespace="http://osb.bancochile.cl/ReversaCosmos/", IsWrapped=true)]
    public partial class ReversaCosmosRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/ReversaCosmos/")]
        public BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.datosHeaderRequest headerRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/ReversaCosmos/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.reqReversaCosmos reqReversaCosmos;
        
        public ReversaCosmosRequest() {
        }
        
        public ReversaCosmosRequest(BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.reqReversaCosmos reqReversaCosmos) {
            this.headerRequest = headerRequest;
            this.reqReversaCosmos = reqReversaCosmos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReversaCosmosResponse", WrapperNamespace="http://osb.bancochile.cl/ReversaCosmos/", IsWrapped=true)]
    public partial class ReversaCosmosResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/ReversaCosmos/")]
        public BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.datosHeaderResponse headerResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/ReversaCosmos/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.respReversaCosmos respReversaCosmos;
        
        public ReversaCosmosResponse() {
        }
        
        public ReversaCosmosResponse(BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.datosHeaderResponse headerResponse, BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.respReversaCosmos respReversaCosmos) {
            this.headerResponse = headerResponse;
            this.respReversaCosmos = respReversaCosmos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReversaCosmosChannel : BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReversaCosmosClient : System.ServiceModel.ClientBase<BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmos>, BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmos {
        
        public ReversaCosmosClient() {
        }
        
        public ReversaCosmosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReversaCosmosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReversaCosmosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReversaCosmosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosResponse BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmos.ReversaCosmos(BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosRequest request) {
            return base.Channel.ReversaCosmos(request);
        }
        
        public BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.datosHeaderResponse ReversaCosmos(BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.reqReversaCosmos reqReversaCosmos, out BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.respReversaCosmos respReversaCosmos) {
            BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosRequest inValue = new BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosRequest();
            inValue.headerRequest = headerRequest;
            inValue.reqReversaCosmos = reqReversaCosmos;
            BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosResponse retVal = ((BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmos)(this)).ReversaCosmos(inValue);
            respReversaCosmos = retVal.respReversaCosmos;
            return retVal.headerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosResponse> BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmos.ReversaCosmosAsync(BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosRequest request) {
            return base.Channel.ReversaCosmosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosResponse> ReversaCosmosAsync(BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.reqReversaCosmos reqReversaCosmos) {
            BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosRequest inValue = new BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmosRequest();
            inValue.headerRequest = headerRequest;
            inValue.reqReversaCosmos = reqReversaCosmos;
            return ((BCH.Comex.Data.DAL.Services.XCFT.ReversaCosmos.ReversaCosmos)(this)).ReversaCosmosAsync(inValue);
        }
    }
}
