//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://osb.bancochile.cl/RenovacionInternet/ObtenerDatosFichaChica/", ConfigurationName="XCFT.ObtenerDatosFichaChica.ObtenerDatosFichaChica")]
    public interface ObtenerDatosFichaChica {
        
        // CODEGEN: Generating message contract since the wrapper name (ObtenerRequest) of message ObtenerRequest does not match the default value (Obtener)
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl//ObtenerDatosFichaChica/Obtener", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerResponse Obtener(BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://osb.bancochile.cl//ObtenerDatosFichaChica/Obtener", ReplyAction="*")]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerResponse> ObtenerAsync(BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosHeaderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosConsumidor consumidorField;
        
        private datosTransaccion transaccionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosConsumidor consumidor {
            get {
                return this.consumidorField;
            }
            set {
                this.consumidorField = value;
                this.RaisePropertyChanged("consumidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public datosTransaccion transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosConsumidor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idAppField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idApp {
            get {
                return this.idAppField;
            }
            set {
                this.idAppField = value;
                this.RaisePropertyChanged("idApp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="datosTransaccion", Namespace="http://osb.bancochile.cl/common/HeaderResponse")]
    public partial class datosTransaccion1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.Nullable<System.DateTime> fechaHoraInicioTrxField;
        
        private System.Nullable<System.DateTime> fechaHoraFinTrxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> fechaHoraInicioTrx {
            get {
                return this.fechaHoraInicioTrxField;
            }
            set {
                this.fechaHoraInicioTrxField = value;
                this.RaisePropertyChanged("fechaHoraInicioTrx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fechaHoraFinTrx {
            get {
                return this.fechaHoraFinTrxField;
            }
            set {
                this.fechaHoraFinTrxField = value;
                this.RaisePropertyChanged("fechaHoraFinTrx");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderResponse")]
    public partial class datosHeaderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosTransaccion1 transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosTransaccion1 transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/common/HeaderRequest")]
    public partial class datosTransaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string internalCodeField;
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaHoraField;
        
        private string canalField;
        
        private string sucursalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("internalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("sucursal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/RenovacionInternet/ObtenerDatosFichaChica/OpObtenerR" +
        "esponse")]
    public partial class respObtener : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Cuerpo1 cuerpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Cuerpo1 Cuerpo {
            get {
                return this.cuerpoField;
            }
            set {
                this.cuerpoField = value;
                this.RaisePropertyChanged("Cuerpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/RenovacionInternet/ObtenerDatosFichaChica/OpObtenerR" +
        "esponse")]
    public partial class Cuerpo1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoRetornoField;
        
        private string rutClienteField;
        
        private string nombreField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string oficinaEjecutivoField;
        
        private string codigoEjecutivoField;
        
        private string nombreEjecutivoField;
        
        private string apellidoPaternoEjecutivoField;
        
        private string apellidoMaternoEjecutivoField;
        
        private string emailEjecutivoField;
        
        private string codigoPaisEjecutivoField;
        
        private string codigoCiudadEjecutivoField;
        
        private string telefonoField;
        
        private string segmentoField;
        
        private string marcaField;
        
        private string bancaField;
        
        private string clasificacionRiesgoField;
        
        private string actividadEconomicaField;
        
        private string categoriaField;
        
        private string codigoSegmentoField;
        
        private string codigoMarcaField;
        
        private string codigoBancaField;
        
        private string codigoActividadEconomicaField;
        
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private string nombreOficinaField;
        
        private string tipoClienteField;
        
        private string sexoField;
        
        private string direccionField;
        
        private string numeroDireccionField;
        
        private string complementoDireccionField;
        
        private string comunaField;
        
        private string ciudadField;
        
        private string regionField;
        
        private string paisField;
        
        private string tipoDespachoField;
        
        private string cuiField;
        
        private string codigoCategoriaField;
        
        private string rowIdDireccionField;
        
        private string codigoPaisFonoPartClienteField;
        
        private string codigoCiudadPartClienteField;
        
        private string fonoParticularClienteField;
        
        private string codigoPaisCelularClienteField;
        
        private string codigoCiudadCelularClienteField;
        
        private string celularParticularClienteField;
        
        private string emailParticularClienteField;
        
        private string codigoPaisFonoComClienteField;
        
        private string codigoCiudadFonoComClienteField;
        
        private string fonoComercialClienteField;
        
        private string emailComercialClienteField;
        
        private string emailAlternativoEjecutivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
                this.RaisePropertyChanged("codigoRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string rutCliente {
            get {
                return this.rutClienteField;
            }
            set {
                this.rutClienteField = value;
                this.RaisePropertyChanged("rutCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string oficinaEjecutivo {
            get {
                return this.oficinaEjecutivoField;
            }
            set {
                this.oficinaEjecutivoField = value;
                this.RaisePropertyChanged("oficinaEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string codigoEjecutivo {
            get {
                return this.codigoEjecutivoField;
            }
            set {
                this.codigoEjecutivoField = value;
                this.RaisePropertyChanged("codigoEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string nombreEjecutivo {
            get {
                return this.nombreEjecutivoField;
            }
            set {
                this.nombreEjecutivoField = value;
                this.RaisePropertyChanged("nombreEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string apellidoPaternoEjecutivo {
            get {
                return this.apellidoPaternoEjecutivoField;
            }
            set {
                this.apellidoPaternoEjecutivoField = value;
                this.RaisePropertyChanged("apellidoPaternoEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string apellidoMaternoEjecutivo {
            get {
                return this.apellidoMaternoEjecutivoField;
            }
            set {
                this.apellidoMaternoEjecutivoField = value;
                this.RaisePropertyChanged("apellidoMaternoEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string emailEjecutivo {
            get {
                return this.emailEjecutivoField;
            }
            set {
                this.emailEjecutivoField = value;
                this.RaisePropertyChanged("emailEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string codigoPaisEjecutivo {
            get {
                return this.codigoPaisEjecutivoField;
            }
            set {
                this.codigoPaisEjecutivoField = value;
                this.RaisePropertyChanged("codigoPaisEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string codigoCiudadEjecutivo {
            get {
                return this.codigoCiudadEjecutivoField;
            }
            set {
                this.codigoCiudadEjecutivoField = value;
                this.RaisePropertyChanged("codigoCiudadEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=13)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
                this.RaisePropertyChanged("segmento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string banca {
            get {
                return this.bancaField;
            }
            set {
                this.bancaField = value;
                this.RaisePropertyChanged("banca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string clasificacionRiesgo {
            get {
                return this.clasificacionRiesgoField;
            }
            set {
                this.clasificacionRiesgoField = value;
                this.RaisePropertyChanged("clasificacionRiesgo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string actividadEconomica {
            get {
                return this.actividadEconomicaField;
            }
            set {
                this.actividadEconomicaField = value;
                this.RaisePropertyChanged("actividadEconomica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string codigoSegmento {
            get {
                return this.codigoSegmentoField;
            }
            set {
                this.codigoSegmentoField = value;
                this.RaisePropertyChanged("codigoSegmento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string codigoMarca {
            get {
                return this.codigoMarcaField;
            }
            set {
                this.codigoMarcaField = value;
                this.RaisePropertyChanged("codigoMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string codigoBanca {
            get {
                return this.codigoBancaField;
            }
            set {
                this.codigoBancaField = value;
                this.RaisePropertyChanged("codigoBanca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string codigoActividadEconomica {
            get {
                return this.codigoActividadEconomicaField;
            }
            set {
                this.codigoActividadEconomicaField = value;
                this.RaisePropertyChanged("codigoActividadEconomica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string nombreOficina {
            get {
                return this.nombreOficinaField;
            }
            set {
                this.nombreOficinaField = value;
                this.RaisePropertyChanged("nombreOficina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string numeroDireccion {
            get {
                return this.numeroDireccionField;
            }
            set {
                this.numeroDireccionField = value;
                this.RaisePropertyChanged("numeroDireccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string complementoDireccion {
            get {
                return this.complementoDireccionField;
            }
            set {
                this.complementoDireccionField = value;
                this.RaisePropertyChanged("complementoDireccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("comuna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string tipoDespacho {
            get {
                return this.tipoDespachoField;
            }
            set {
                this.tipoDespachoField = value;
                this.RaisePropertyChanged("tipoDespacho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public string cui {
            get {
                return this.cuiField;
            }
            set {
                this.cuiField = value;
                this.RaisePropertyChanged("cui");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string codigoCategoria {
            get {
                return this.codigoCategoriaField;
            }
            set {
                this.codigoCategoriaField = value;
                this.RaisePropertyChanged("codigoCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public string rowIdDireccion {
            get {
                return this.rowIdDireccionField;
            }
            set {
                this.rowIdDireccionField = value;
                this.RaisePropertyChanged("rowIdDireccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public string CodigoPaisFonoPartCliente {
            get {
                return this.codigoPaisFonoPartClienteField;
            }
            set {
                this.codigoPaisFonoPartClienteField = value;
                this.RaisePropertyChanged("CodigoPaisFonoPartCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public string CodigoCiudadPartCliente {
            get {
                return this.codigoCiudadPartClienteField;
            }
            set {
                this.codigoCiudadPartClienteField = value;
                this.RaisePropertyChanged("CodigoCiudadPartCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public string FonoParticularCliente {
            get {
                return this.fonoParticularClienteField;
            }
            set {
                this.fonoParticularClienteField = value;
                this.RaisePropertyChanged("FonoParticularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public string CodigoPaisCelularCliente {
            get {
                return this.codigoPaisCelularClienteField;
            }
            set {
                this.codigoPaisCelularClienteField = value;
                this.RaisePropertyChanged("CodigoPaisCelularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public string CodigoCiudadCelularCliente {
            get {
                return this.codigoCiudadCelularClienteField;
            }
            set {
                this.codigoCiudadCelularClienteField = value;
                this.RaisePropertyChanged("CodigoCiudadCelularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public string CelularParticularCliente {
            get {
                return this.celularParticularClienteField;
            }
            set {
                this.celularParticularClienteField = value;
                this.RaisePropertyChanged("CelularParticularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public string EmailParticularCliente {
            get {
                return this.emailParticularClienteField;
            }
            set {
                this.emailParticularClienteField = value;
                this.RaisePropertyChanged("EmailParticularCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public string CodigoPaisFonoComCliente {
            get {
                return this.codigoPaisFonoComClienteField;
            }
            set {
                this.codigoPaisFonoComClienteField = value;
                this.RaisePropertyChanged("CodigoPaisFonoComCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public string CodigoCiudadFonoComCliente {
            get {
                return this.codigoCiudadFonoComClienteField;
            }
            set {
                this.codigoCiudadFonoComClienteField = value;
                this.RaisePropertyChanged("CodigoCiudadFonoComCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=48)]
        public string FonoComercialCliente {
            get {
                return this.fonoComercialClienteField;
            }
            set {
                this.fonoComercialClienteField = value;
                this.RaisePropertyChanged("FonoComercialCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public string EmailComercialCliente {
            get {
                return this.emailComercialClienteField;
            }
            set {
                this.emailComercialClienteField = value;
                this.RaisePropertyChanged("EmailComercialCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=50)]
        public string EmailAlternativoEjecutivo {
            get {
                return this.emailAlternativoEjecutivoField;
            }
            set {
                this.emailAlternativoEjecutivoField = value;
                this.RaisePropertyChanged("EmailAlternativoEjecutivo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://osb.bancochile.cl/ESB/RenovacionInternet/ObtenerDatosFichaChica/OpObtenerR" +
        "equest")]
    public partial class reqObtener : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Cuerpo cuerpoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Cuerpo Cuerpo {
            get {
                return this.cuerpoField;
            }
            set {
                this.cuerpoField = value;
                this.RaisePropertyChanged("Cuerpo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://osb.bancochile.cl/ESB/RenovacionInternet/ObtenerDatosFichaChica/OpObtenerR" +
        "equest")]
    public partial class Cuerpo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutClienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rutCliente {
            get {
                return this.rutClienteField;
            }
            set {
                this.rutClienteField = value;
                this.RaisePropertyChanged("rutCliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerRequest", WrapperNamespace="http://osb.bancochile.cl/RenovacionInternet/ObtenerDatosFichaChica/", IsWrapped=true)]
    public partial class ObtenerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/RenovacionInternet/ObtenerDatosFichaChica/")]
        public BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.datosHeaderRequest headerRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/RenovacionInternet/ObtenerDatosFichaChica/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.reqObtener reqObtener;
        
        public ObtenerRequest() {
        }
        
        public ObtenerRequest(BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.reqObtener reqObtener) {
            this.headerRequest = headerRequest;
            this.reqObtener = reqObtener;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerResponse", WrapperNamespace="http://osb.bancochile.cl/RenovacionInternet/ObtenerDatosFichaChica/", IsWrapped=true)]
    public partial class ObtenerResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://osb.bancochile.cl/RenovacionInternet/ObtenerDatosFichaChica/")]
        public BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.datosHeaderResponse headerResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://osb.bancochile.cl/RenovacionInternet/ObtenerDatosFichaChica/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.respObtener respObtener;
        
        public ObtenerResponse() {
        }
        
        public ObtenerResponse(BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.datosHeaderResponse headerResponse, BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.respObtener respObtener) {
            this.headerResponse = headerResponse;
            this.respObtener = respObtener;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ObtenerDatosFichaChicaChannel : BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerDatosFichaChica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerDatosFichaChicaClient : System.ServiceModel.ClientBase<BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerDatosFichaChica>, BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerDatosFichaChica {
        
        public ObtenerDatosFichaChicaClient() {
        }
        
        public ObtenerDatosFichaChicaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObtenerDatosFichaChicaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObtenerDatosFichaChicaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObtenerDatosFichaChicaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerResponse BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerDatosFichaChica.Obtener(BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerRequest request) {
            return base.Channel.Obtener(request);
        }
        
        public BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.datosHeaderResponse Obtener(BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.reqObtener reqObtener, out BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.respObtener respObtener) {
            BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerRequest inValue = new BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerRequest();
            inValue.headerRequest = headerRequest;
            inValue.reqObtener = reqObtener;
            BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerResponse retVal = ((BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerDatosFichaChica)(this)).Obtener(inValue);
            respObtener = retVal.respObtener;
            return retVal.headerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerResponse> BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerDatosFichaChica.ObtenerAsync(BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerRequest request) {
            return base.Channel.ObtenerAsync(request);
        }
        
        public System.Threading.Tasks.Task<BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerResponse> ObtenerAsync(BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.datosHeaderRequest headerRequest, BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.reqObtener reqObtener) {
            BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerRequest inValue = new BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerRequest();
            inValue.headerRequest = headerRequest;
            inValue.reqObtener = reqObtener;
            return ((BCH.Comex.Data.DAL.Services.XCFT.ObtenerDatosFichaChica.ObtenerDatosFichaChica)(this)).ObtenerAsync(inValue);
        }
    }
}
