//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Cext01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sce_dad
    {
        public string id_party { get; set; }
        public decimal id_dir { get; set; }
        public bool borrado { get; set; }
        public string direccion { get; set; }
        public string comuna { get; set; }
        public decimal cod_comuna { get; set; }
        public string cod_postal { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string pais { get; set; }
        public decimal cod_pais { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string telex { get; set; }
        public decimal envio_sce { get; set; }
        public decimal recibe_sce { get; set; }
        public string cas_postal { get; set; }
        public string cas_banco { get; set; }
        public string crea_costo { get; set; }
        public string crea_user { get; set; }
        public string email { get; set; }
    }
}
