//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Cext01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sce_mcd
    {
        public string codcct { get; set; }
        public string codpro { get; set; }
        public string codesp { get; set; }
        public string codofi { get; set; }
        public string codope { get; set; }
        public decimal codneg { get; set; }
        public decimal codsec { get; set; }
        public decimal nrorpt { get; set; }
        public System.DateTime fecmov { get; set; }
        public string cencos { get; set; }
        public string codusr { get; set; }
        public decimal nroimp { get; set; }
        public decimal estado { get; set; }
        public string tipmcd { get; set; }
        public decimal idncta { get; set; }
        public string nemcta { get; set; }
        public string numcta { get; set; }
        public decimal codmon { get; set; }
        public string nemmon { get; set; }
        public decimal mtomcd { get; set; }
        public string cod_dh { get; set; }
        public decimal numemb { get; set; }
        public string prtcli { get; set; }
        public decimal indcli { get; set; }
        public string rutcli { get; set; }
        public string prtbco { get; set; }
        public decimal indbco { get; set; }
        public string rutbco { get; set; }
        public string swibco { get; set; }
        public decimal codbco { get; set; }
        public string numcct { get; set; }
        public string numlin { get; set; }
        public System.DateTime fecori { get; set; }
        public System.DateTime fecven { get; set; }
        public System.DateTime fecint { get; set; }
        public bool tasfij { get; set; }
        public decimal mtotas { get; set; }
        public decimal ofides { get; set; }
        public decimal numpar { get; set; }
        public decimal tipmov { get; set; }
        public string nroref { get; set; }
        public decimal tipcam { get; set; }
        public decimal nrotop { get; set; }
        public decimal indtop { get; set; }
        public bool intcit { get; set; }
        public bool intcvt { get; set; }
        public bool intcap { get; set; }
        public bool intctd { get; set; }
        public bool intpos { get; set; }
        public bool intcdr { get; set; }
        public bool mcdvig { get; set; }
        public Nullable<decimal> enlinea { get; set; }
        public string rutais { get; set; }
        public Nullable<decimal> nrofac { get; set; }
    }
}
