//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Cext01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sce_dfc
    {
        public decimal coddfc { get; set; }
        public string desdfc { get; set; }
        public Nullable<decimal> codext { get; set; }
    }
}
