//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Cext01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sce_tccs
    {
        public decimal codmt { get; set; }
        public string codcam { get; set; }
        public string descam { get; set; }
        public bool camman { get; set; }
        public decimal numlin { get; set; }
        public decimal lenlin { get; set; }
        public decimal lentot { get; set; }
    }
}
