//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Cext01
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sce_codtran_ft
    {
        public decimal nro_trx { get; set; }
        public string cod_sistema { get; set; }
        public decimal cod_bch { get; set; }
        public string cod_ext { get; set; }
        public string cod_prod { get; set; }
        public string cod_trx_fc { get; set; }
        public string moneda { get; set; }
        public string cr_dr { get; set; }
        public string descrip { get; set; }
        public string glosa_cosmos { get; set; }
        public string cod_swf { get; set; }
        public string cod_trx_cosmos { get; set; }
    }
}
