//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public string id { get; set; }
        public string name { get; set; }
        public string grupo_id { get; set; }
        public string ad_group_name { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string parameters { get; set; }
    
        public virtual GrupoAplicacion Grupo { get; set; }
    }
}
