//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Swift
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_caracter_error
    {
        public int valor_ascii { get; set; }
        public string caracter { get; set; }
        public string descripcion { get; set; }
    }
}
