//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Swift
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_formatos
    {
        public string tipo_msg_fmt { get; set; }
        public int orden_fmt { get; set; }
        public string secuencia_fmt { get; set; }
        public int repeticion_fmt { get; set; }
        public string tag_fmt { get; set; }
        public string status_fmt { get; set; }
    }
}
