//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCH.Comex.Core.Entities.Swift
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_monedas
    {
        public string cod_moneda_sw { get; set; }
        public Nullable<short> decimales { get; set; }
        public string nombre_moneda { get; set; }
        public string cod_moneda_banco { get; set; }
        public string uso_moneda_banco { get; set; }
    }
}
